const DSLR_Photograpgy: Record<string, any> = {
  Beach_Vacation: {
    environment_title: "Beach_Vacation",
    images: [
      {
        original_file_name: "Beach_Vacation (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35229,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#22657c",
        secondary: "#bea07d",
        tertiary: "#c7d4d9",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Beach_Vacation (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34649,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#2b678e",
        secondary: "#d4bfa6",
        tertiary: "#9f876f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Beach_Vacation (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35473,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#1f5e71",
        secondary: "#cbaf92",
        tertiary: "#dfe0e2",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Beach_Vacation (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43232,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#27586e",
        secondary: "#bf9870",
        tertiary: "#b6d0e0",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Beach_Vacation (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7884496,
        file_size_megabytes: 7.52,
        width: 3072,
        height: 5472,
        primary: "#22657c",
        secondary: "#bea07d",
        tertiary: "#c7d4da",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Beach_Vacation (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8477025,
        file_size_megabytes: 8.08,
        width: 3072,
        height: 5472,
        primary: "#2b688f",
        secondary: "#d2bda4",
        tertiary: "#719ebf",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Beach_Vacation (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7971212,
        file_size_megabytes: 7.6,
        width: 3072,
        height: 5472,
        primary: "#1e5e72",
        secondary: "#cbaf92",
        tertiary: "#dedfe2",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Beach_Vacation (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8946470,
        file_size_megabytes: 8.53,
        width: 3072,
        height: 5472,
        primary: "#27576f",
        secondary: "#bf9870",
        tertiary: "#b5cfe0",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Corporate_Meeting: {
    environment_title: "Corporate_Meeting",
    images: [
      {
        original_file_name: "Corporate_Meeting (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49397,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#323938",
        secondary: "#b4bab9",
        tertiary: "#dee1e1",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Corporate_Meeting (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45221,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#2a3233",
        secondary: "#e2e6e5",
        tertiary: "#b4c3c4",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Corporate_Meeting (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46507,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#192a2a",
        secondary: "#d3d9d7",
        tertiary: "#4e5252",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Corporate_Meeting (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51881,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#2f3131",
        secondary: "#b3babb",
        tertiary: "#dededc",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Corporate_Meeting (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6975420,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#323938",
        secondary: "#b4bab8",
        tertiary: "#dee1e1",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Corporate_Meeting (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6758305,
        file_size_megabytes: 6.45,
        width: 3072,
        height: 5472,
        primary: "#2b3233",
        secondary: "#e2e6e5",
        tertiary: "#b4c4c5",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Corporate_Meeting (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6854200,
        file_size_megabytes: 6.54,
        width: 3072,
        height: 5472,
        primary: "#1a2a2b",
        secondary: "#d6dbd9",
        tertiary: "#667a7a",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Corporate_Meeting (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7453793,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#2f3130",
        secondary: "#b3bbbc",
        tertiary: "#dddddb",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Creative_Workspace: {
    environment_title: "Creative_Workspace",
    images: [
      {
        original_file_name: "Creative_Workspace (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46073,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d9af88",
        secondary: "#1b110c",
        tertiary: "#8a5e41",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Creative_Workspace (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55056,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dcbe9f",
        secondary: "#9fa79c",
        tertiary: "#23120e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Creative_Workspace (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52270,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e4d1b8",
        secondary: "#25130e",
        tertiary: "#99a49c",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Creative_Workspace (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45614,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dac5b0",
        secondary: "#231814",
        tertiary: "#88634e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Creative_Workspace (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7225893,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#d9af87",
        secondary: "#1b110c",
        tertiary: "#8a5e40",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Creative_Workspace (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7762249,
        file_size_megabytes: 7.4,
        width: 3072,
        height: 5472,
        primary: "#ddbd9e",
        secondary: "#9ea89c",
        tertiary: "#22120d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Creative_Workspace (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7453865,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#e4d1b7",
        secondary: "#25130e",
        tertiary: "#99a49d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Creative_Workspace (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7495287,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#dbc4af",
        secondary: "#221813",
        tertiary: "#88624d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Fitness_Routine: {
    environment_title: "Fitness_Routine",
    images: [
      {
        original_file_name: "Fitness_Routine (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45220,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e4dfd4",
        secondary: "#221e1d",
        tertiary: "#a7bbc8",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Fitness_Routine (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40403,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e7e0d0",
        secondary: "#181819",
        tertiary: "#87725f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Fitness_Routine (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42754,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e1d5c5",
        secondary: "#4f3c36",
        tertiary: "#917464",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Fitness_Routine (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40948,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbcdc0",
        secondary: "#1a1316",
        tertiary: "#6c6a62",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Fitness_Routine (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7368042,
        file_size_megabytes: 7.03,
        width: 3072,
        height: 5472,
        primary: "#e5dfd4",
        secondary: "#211d1d",
        tertiary: "#a7bbc9",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Fitness_Routine (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6504992,
        file_size_megabytes: 6.2,
        width: 3072,
        height: 5472,
        primary: "#e7e0d0",
        secondary: "#181819",
        tertiary: "#88725f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Fitness_Routine (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7744392,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#e0d4c3",
        secondary: "#4f3c36",
        tertiary: "#917464",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Fitness_Routine (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7099475,
        file_size_megabytes: 6.77,
        width: 3072,
        height: 5472,
        primary: "#dbcdbf",
        secondary: "#1a1416",
        tertiary: "#6c6a62",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Grocery_Shopping: {
    environment_title: "Grocery_Shopping",
    images: [
      {
        original_file_name: "Grocery_Shopping (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53116,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e6d7a3",
        secondary: "#734f26",
        tertiary: "#211b0e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Grocery_Shopping (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57272,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e3bd85",
        secondary: "#5d401f",
        tertiary: "#18170c",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Grocery_Shopping (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58653,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#20271f",
        secondary: "#eadab1",
        tertiary: "#6f4421",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Grocery_Shopping (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59776,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e1b67c",
        secondary: "#282816",
        tertiary: "#9a693e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Grocery_Shopping (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8889869,
        file_size_megabytes: 8.48,
        width: 3072,
        height: 5472,
        primary: "#e6d7a2",
        secondary: "#734d23",
        tertiary: "#211b0d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Grocery_Shopping (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8644996,
        file_size_megabytes: 8.24,
        width: 3072,
        height: 5472,
        primary: "#e4bc83",
        secondary: "#5d401f",
        tertiary: "#17180b",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Grocery_Shopping (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8529827,
        file_size_megabytes: 8.13,
        width: 3072,
        height: 5472,
        primary: "#1f271f",
        secondary: "#eadab0",
        tertiary: "#6f441f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Grocery_Shopping (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8584160,
        file_size_megabytes: 8.19,
        width: 3072,
        height: 5472,
        primary: "#e1b67a",
        secondary: "#282815",
        tertiary: "#9a693d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Healthy_Breakfast: {
    environment_title: "Healthy_Breakfast",
    images: [
      {
        original_file_name: "Healthy_Breakfast (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46727,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a27652",
        secondary: "#27140e",
        tertiary: "#e2d7bc",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Healthy_Breakfast (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43170,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#aa8c72",
        secondary: "#2d1b12",
        tertiary: "#dbd7d2",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Healthy_Breakfast (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46920,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a1856d",
        secondary: "#282612",
        tertiary: "#dfddc8",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Healthy_Breakfast (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44722,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#231510",
        secondary: "#aa8564",
        tertiary: "#dadbd2",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Healthy_Breakfast (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8267421,
        file_size_megabytes: 7.88,
        width: 3072,
        height: 5472,
        primary: "#a27651",
        secondary: "#27140d",
        tertiary: "#e3d7bc",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Healthy_Breakfast (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7617627,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#aa8c72",
        secondary: "#2d1b12",
        tertiary: "#dad7d3",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Healthy_Breakfast (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7791076,
        file_size_megabytes: 7.43,
        width: 3072,
        height: 5472,
        primary: "#a0856d",
        secondary: "#272612",
        tertiary: "#dfddc8",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Healthy_Breakfast (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7614661,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#231510",
        secondary: "#ab8564",
        tertiary: "#dadbd2",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Pet_Love: {
    environment_title: "Pet_Love",
    images: [
      {
        original_file_name: "Pet_Love (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58282,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d4d46e",
        secondary: "#313b0d",
        tertiary: "#938d32",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Pet_Love (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52670,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#3d5017",
        secondary: "#d5d169",
        tertiary: "#8e8830",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Pet_Love (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59345,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#333c0f",
        secondary: "#d3d580",
        tertiary: "#919b30",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Pet_Love (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62605,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#333c10",
        secondary: "#cecb77",
        tertiary: "#93952d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Pet_Love (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8740451,
        file_size_megabytes: 8.34,
        width: 3072,
        height: 5472,
        primary: "#d4d46c",
        secondary: "#313b0d",
        tertiary: "#938d30",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Pet_Love (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8579571,
        file_size_megabytes: 8.18,
        width: 3072,
        height: 5472,
        primary: "#3d5016",
        secondary: "#d6d068",
        tertiary: "#8e872e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Pet_Love (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8706816,
        file_size_megabytes: 8.3,
        width: 3072,
        height: 5472,
        primary: "#333c0f",
        secondary: "#d3d57e",
        tertiary: "#919a2e",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Pet_Love (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8981762,
        file_size_megabytes: 8.57,
        width: 3072,
        height: 5472,
        primary: "#333c0f",
        secondary: "#ceca75",
        tertiary: "#93952a",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Productivity_at_Work: {
    environment_title: "Productivity_at_Work",
    images: [
      {
        original_file_name: "Productivity_at_Work (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32172,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e2d8c4",
        secondary: "#a8a894",
        tertiary: "#8c7b67",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Productivity_at_Work (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42969,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e3c8ae",
        secondary: "#acb1aa",
        tertiary: "#1d1b15",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Productivity_at_Work (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34819,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e9e5d8",
        secondary: "#251b14",
        tertiary: "#afb4a6",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Productivity_at_Work (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34533,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e7d2ba",
        secondary: "#a7aca6",
        tertiary: "#8c8070",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Productivity_at_Work (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6011929,
        file_size_megabytes: 5.73,
        width: 3072,
        height: 5472,
        primary: "#e3d7c4",
        secondary: "#a9a895",
        tertiary: "#8c7a67",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Productivity_at_Work (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7117605,
        file_size_megabytes: 6.79,
        width: 3072,
        height: 5472,
        primary: "#e2c8ad",
        secondary: "#adb1aa",
        tertiary: "#1d1b15",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Productivity_at_Work (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6464519,
        file_size_megabytes: 6.17,
        width: 3072,
        height: 5472,
        primary: "#eae5d8",
        secondary: "#241a13",
        tertiary: "#afb4a6",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Productivity_at_Work (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6431249,
        file_size_megabytes: 6.13,
        width: 3072,
        height: 5472,
        primary: "#e7d2ba",
        secondary: "#a7aca6",
        tertiary: "#8d8070",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Remote_Work_Bliss: {
    environment_title: "Remote_Work_Bliss",
    images: [
      {
        original_file_name: "Remote_Work_Bliss (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48516,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dcd0c3",
        secondary: "#1e1611",
        tertiary: "#a6aca8",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Remote_Work_Bliss (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41638,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbc9b7",
        secondary: "#23190f",
        tertiary: "#a7a89c",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Remote_Work_Bliss (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41173,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c9ab87",
        secondary: "#21130e",
        tertiary: "#643f1f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Remote_Work_Bliss (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42090,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e1cdb8",
        secondary: "#1d1510",
        tertiary: "#8c6950",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Remote_Work_Bliss (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7288838,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#dccfc2",
        secondary: "#1e1510",
        tertiary: "#966e51",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Remote_Work_Bliss (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7025635,
        file_size_megabytes: 6.7,
        width: 3072,
        height: 5472,
        primary: "#dbc9b7",
        secondary: "#23180f",
        tertiary: "#a6a89c",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Remote_Work_Bliss (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7306718,
        file_size_megabytes: 6.97,
        width: 3072,
        height: 5472,
        primary: "#20130e",
        secondary: "#c49664",
        tertiary: "#ccd6d4",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Remote_Work_Bliss (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7011962,
        file_size_megabytes: 6.69,
        width: 3072,
        height: 5472,
        primary: "#e1ccb7",
        secondary: "#1d1510",
        tertiary: "#8c6950",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  },
  Young_Entrepreneur: {
    environment_title: "Young_Entrepreneur",
    images: [
      {
        original_file_name: "Young_Entrepreneur (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45980,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbbea1",
        secondary: "#1a1c13",
        tertiary: "#9ea897",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Young_Entrepreneur (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46752,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e2cfb8",
        secondary: "#b0b09e",
        tertiary: "#978067",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Young_Entrepreneur (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44977,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e4c3a5",
        secondary: "#acb1a5",
        tertiary: "#22180f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Young_Entrepreneur (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52065,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dec8b1",
        secondary: "#a6a997",
        tertiary: "#241c11",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "min"
      },
      {
        original_file_name: "Young_Entrepreneur (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6976325,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#dbbea0",
        secondary: "#9ea897",
        tertiary: "#1a1c12",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Young_Entrepreneur (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6841642,
        file_size_megabytes: 6.52,
        width: 3072,
        height: 5472,
        primary: "#e2cfb7",
        secondary: "#b0b09e",
        tertiary: "#978066",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Young_Entrepreneur (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7004623,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#e4c3a4",
        secondary: "#acb1a5",
        tertiary: "#1f160d",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      },
      {
        original_file_name: "Young_Entrepreneur (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7495498,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#dec7b1",
        secondary: "#a6a996",
        tertiary: "#20190f",
        Branch: "DSLR",
        FolderName: "Photography",
        Type: "max"
      }
    ]
  }
};
export default DSLR_Photograpgy;
