const Portrait_Bokeh: Record<string, any> = {
  Evening_Elegance: {
    environment_title: "Evening_Elegance",
    images: [
      {
        original_file_name: "Evening_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 30923,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#db9550",
        secondary: "#7b4925",
        tertiary: "#0e0c0e",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Evening_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34458,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#da9d5b",
        secondary: "#180e0b",
        tertiary: "#7f4823",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Evening_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32847,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#dca366",
        secondary: "#733f19",
        tertiary: "#140a07",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Evening_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29938,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#dd9c5a",
        secondary: "#150c09",
        tertiary: "#753f19",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Evening_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6653764,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#db944f",
        secondary: "#7b4925",
        tertiary: "#0e0c0e",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Evening_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6711757,
        file_size_megabytes: 6.4,
        width: 3072,
        height: 5472,
        primary: "#db9c59",
        secondary: "#180e0b",
        tertiary: "#7f4723",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Evening_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6473491,
        file_size_megabytes: 6.17,
        width: 3072,
        height: 5472,
        primary: "#dca265",
        secondary: "#733e18",
        tertiary: "#140a07",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Evening_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6728599,
        file_size_megabytes: 6.42,
        width: 3072,
        height: 5472,
        primary: "#de9c59",
        secondary: "#150c0a",
        tertiary: "#753e19",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Golden_Hour_Glow: {
    environment_title: "Golden_Hour_Glow",
    images: [
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38203,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#f3d396",
        secondary: "#633812",
        tertiary: "#d78a38",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34030,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#f4d493",
        secondary: "#6c3a13",
        tertiary: "#e19544",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40636,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#754019",
        secondary: "#f6d68e",
        tertiary: "#e49955",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34751,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#5d3515",
        secondary: "#f3d598",
        tertiary: "#d48835",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7614778,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#f4d395",
        secondary: "#633712",
        tertiary: "#d68a37",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7463278,
        file_size_megabytes: 7.12,
        width: 3072,
        height: 5472,
        primary: "#f4d493",
        secondary: "#6b3a12",
        tertiary: "#e29543",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7728987,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#754019",
        secondary: "#f7d68d",
        tertiary: "#e59853",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7637328,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#5e3515",
        secondary: "#f3d598",
        tertiary: "#d58834",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Rainy_Day_Reflection: {
    environment_title: "Rainy_Day_Reflection",
    images: [
      {
        original_file_name: "Rainy_Day_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47566,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d2c9be",
        secondary: "#272723",
        tertiary: "#85705e",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Day_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39086,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#9fb8c6",
        secondary: "#31231c",
        tertiary: "#d7cdbe",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Day_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39239,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#32241d",
        secondary: "#86a0b1",
        tertiary: "#d7cdbe",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Day_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40713,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c7bcb2",
        secondary: "#96a5a6",
        tertiary: "#1b1c1f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Day_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7745300,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#d2c8be",
        secondary: "#272723",
        tertiary: "#85715f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Day_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7389559,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#9fb8c6",
        secondary: "#31241c",
        tertiary: "#d7cdbd",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Day_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7440048,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#32241d",
        secondary: "#86a0b1",
        tertiary: "#d7cdbd",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Day_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7586108,
        file_size_megabytes: 7.23,
        width: 3072,
        height: 5472,
        primary: "#c7bcb2",
        secondary: "#96a4a6",
        tertiary: "#1b1c1f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Rustic_Charm: {
    environment_title: "Rustic_Charm",
    images: [
      {
        original_file_name: "Rustic_Charm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47347,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#604833",
        secondary: "#d9b282",
        tertiary: "#201e17",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44382,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbb07f",
        secondary: "#322921",
        tertiary: "#966640",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43159,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#675f2e",
        secondary: "#dfb892",
        tertiary: "#8899b1",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50024,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#9d7446",
        secondary: "#e1ddd3",
        tertiary: "#643017",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8973796,
        file_size_megabytes: 8.56,
        width: 3072,
        height: 5472,
        primary: "#604833",
        secondary: "#d9b283",
        tertiary: "#201e17",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8531907,
        file_size_megabytes: 8.14,
        width: 3072,
        height: 5472,
        primary: "#dbaf7e",
        secondary: "#322921",
        tertiary: "#96653f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8290292,
        file_size_megabytes: 7.91,
        width: 3072,
        height: 5472,
        primary: "#675f2e",
        secondary: "#dfb792",
        tertiary: "#8799b1",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8563338,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#9d7445",
        secondary: "#e1ddd3",
        tertiary: "#2c2321",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Starry_Night_Gaze: {
    environment_title: "Starry_Night_Gaze",
    images: [
      {
        original_file_name: "Starry_Night_Gaze (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41116,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#aa865f",
        secondary: "#15222d",
        tertiary: "#667773",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Starry_Night_Gaze (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37526,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#ca9263",
        secondary: "#151b25",
        tertiary: "#6c4a38",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Starry_Night_Gaze (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35285,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#111a27",
        secondary: "#c38757",
        tertiary: "#5d3929",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Starry_Night_Gaze (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33851,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c68a64",
        secondary: "#131a22",
        tertiary: "#134a65",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Starry_Night_Gaze (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7264311,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#aa855d",
        secondary: "#15222c",
        tertiary: "#667773",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Starry_Night_Gaze (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7299212,
        file_size_megabytes: 6.96,
        width: 3072,
        height: 5472,
        primary: "#ca9262",
        secondary: "#151b25",
        tertiary: "#6c4a38",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Starry_Night_Gaze (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7245217,
        file_size_megabytes: 6.91,
        width: 3072,
        height: 5472,
        primary: "#111a27",
        secondary: "#c48656",
        tertiary: "#5e3929",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Starry_Night_Gaze (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7710377,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#c68a63",
        secondary: "#131a23",
        tertiary: "#124966",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Street_Performer: {
    environment_title: "Street_Performer",
    images: [
      {
        original_file_name: "Street_Performer (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41510,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#df9b58",
        secondary: "#1b181f",
        tertiary: "#885033",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Street_Performer (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36388,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d8954e",
        secondary: "#18141d",
        tertiary: "#815334",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Street_Performer (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34763,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#daaa7c",
        secondary: "#1c151a",
        tertiary: "#804c31",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Street_Performer (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39925,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#deb089",
        secondary: "#221414",
        tertiary: "#915a40",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Street_Performer (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7795444,
        file_size_megabytes: 7.43,
        width: 3072,
        height: 5472,
        primary: "#df9b57",
        secondary: "#1b181f",
        tertiary: "#885032",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Street_Performer (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7468216,
        file_size_megabytes: 7.12,
        width: 3072,
        height: 5472,
        primary: "#d8944c",
        secondary: "#18141d",
        tertiary: "#815333",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Street_Performer (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6949084,
        file_size_megabytes: 6.63,
        width: 3072,
        height: 5472,
        primary: "#daa97b",
        secondary: "#1c151a",
        tertiary: "#804c31",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Street_Performer (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7286987,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#deb087",
        secondary: "#211414",
        tertiary: "#915a40",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Sunlit_Smiles: {
    environment_title: "Sunlit_Smiles",
    images: [
      {
        original_file_name: "Sunlit_Smiles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40937,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#5e4725",
        secondary: "#dec68c",
        tertiary: "#1e210a",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Sunlit_Smiles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41027,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d7be79",
        secondary: "#2a2a11",
        tertiary: "#897030",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Sunlit_Smiles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42634,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dab587",
        secondary: "#2c2810",
        tertiary: "#916a3a",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Sunlit_Smiles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40084,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d9b680",
        secondary: "#322e15",
        tertiary: "#967349",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Sunlit_Smiles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7754118,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#5e4725",
        secondary: "#dfc68c",
        tertiary: "#1e210a",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Sunlit_Smiles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7918172,
        file_size_megabytes: 7.55,
        width: 3072,
        height: 5472,
        primary: "#d8bd79",
        secondary: "#2a2a11",
        tertiary: "#896f2f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Sunlit_Smiles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7843184,
        file_size_megabytes: 7.48,
        width: 3072,
        height: 5472,
        primary: "#dab486",
        secondary: "#2c2810",
        tertiary: "#916a38",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Sunlit_Smiles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7816537,
        file_size_megabytes: 7.45,
        width: 3072,
        height: 5472,
        primary: "#d9b57f",
        secondary: "#322e15",
        tertiary: "#967349",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Urban_Elegance: {
    environment_title: "Urban_Elegance",
    images: [
      {
        original_file_name: "Urban_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28365,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d0ad89",
        secondary: "#191f2b",
        tertiary: "#737167",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Urban_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28234,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ca9a74",
        secondary: "#1c1c22",
        tertiary: "#546878",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Urban_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29482,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d5b797",
        secondary: "#131720",
        tertiary: "#63b6c1",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Urban_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31319,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#daab81",
        secondary: "#11141e",
        tertiary: "#104f72",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Urban_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7216706,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#d0ac88",
        secondary: "#1a1f2b",
        tertiary: "#737067",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Urban_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7140751,
        file_size_megabytes: 6.81,
        width: 3072,
        height: 5472,
        primary: "#cb9974",
        secondary: "#1c1c22",
        tertiary: "#556978",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Urban_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7251483,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#d5b797",
        secondary: "#131720",
        tertiary: "#62b7c2",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Urban_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7075155,
        file_size_megabytes: 6.75,
        width: 3072,
        height: 5472,
        primary: "#daaa80",
        secondary: "#11141e",
        tertiary: "#104f72",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Vibrant_Festival: {
    environment_title: "Vibrant_Festival",
    images: [
      {
        original_file_name: "Vibrant_Festival (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43433,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e79c4b",
        secondary: "#56bdea",
        tertiary: "#406dba",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Vibrant_Festival (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41584,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#de6735",
        secondary: "#1c1821",
        tertiary: "#8a3e32",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Vibrant_Festival (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41671,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dd6a3a",
        secondary: "#8f432c",
        tertiary: "#131322",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Vibrant_Festival (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46730,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#df5b24",
        secondary: "#211621",
        tertiary: "#933825",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Vibrant_Festival (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8034700,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#e79c4a",
        secondary: "#55bceb",
        tertiary: "#406cba",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Vibrant_Festival (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7704484,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#de6634",
        secondary: "#1b1821",
        tertiary: "#8a3d31",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Vibrant_Festival (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7557359,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#dd6938",
        secondary: "#8f432c",
        tertiary: "#131322",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Vibrant_Festival (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8066276,
        file_size_megabytes: 7.69,
        width: 3072,
        height: 5472,
        primary: "#e05a23",
        secondary: "#201721",
        tertiary: "#933824",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Wanderers_Journey: {
    environment_title: "Wanderers_Journey",
    images: [
      {
        original_file_name: "Wanderers_Journey (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37377,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e1bb8f",
        secondary: "#5e5943",
        tertiary: "#1b262e",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Wanderers_Journey (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41102,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d4b68c",
        secondary: "#263535",
        tertiary: "#907247",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Wanderers_Journey (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36893,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#414b42",
        secondary: "#cd9f70",
        tertiary: "#8e6837",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Wanderers_Journey (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42949,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#4b4b3e",
        secondary: "#d7b78c",
        tertiary: "#958058",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Wanderers_Journey (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7540359,
        file_size_megabytes: 7.19,
        width: 3072,
        height: 5472,
        primary: "#e1bb8f",
        secondary: "#5e5943",
        tertiary: "#1a272e",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Wanderers_Journey (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7859185,
        file_size_megabytes: 7.5,
        width: 3072,
        height: 5472,
        primary: "#d4b58b",
        secondary: "#263534",
        tertiary: "#917246",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Wanderers_Journey (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7561724,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#414b42",
        secondary: "#cd9f6f",
        tertiary: "#8e6837",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Wanderers_Journey (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7833356,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#4b4b3e",
        secondary: "#d8b78c",
        tertiary: "#957f58",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  },
  Winter_Warmth: {
    environment_title: "Winter_Warmth",
    images: [
      {
        original_file_name: "Winter_Warmth (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38341,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a9a7a6",
        secondary: "#1c1213",
        tertiary: "#513832",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Winter_Warmth (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31436,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b2b3b6",
        secondary: "#32261e",
        tertiary: "#623c28",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Winter_Warmth (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40935,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dcccc3",
        secondary: "#868280",
        tertiary: "#1d2122",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Winter_Warmth (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35591,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b7b5b6",
        secondary: "#202227",
        tertiary: "#5f4940",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "min"
      },
      {
        original_file_name: "Winter_Warmth (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7632890,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#a9a7a6",
        secondary: "#1c1213",
        tertiary: "#513832",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Winter_Warmth (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7024621,
        file_size_megabytes: 6.7,
        width: 3072,
        height: 5472,
        primary: "#b2b4b7",
        secondary: "#33261e",
        tertiary: "#623c28",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Winter_Warmth (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8102924,
        file_size_megabytes: 7.73,
        width: 3072,
        height: 5472,
        primary: "#282d2e",
        secondary: "#717171",
        tertiary: "#e0d1c9",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      },
      {
        original_file_name: "Winter_Warmth (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7501230,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#b7b5b6",
        secondary: "#202227",
        tertiary: "#5f493f",
        Branch: "Portrait",
        FolderName: "Bokeh",
        Type: "max"
      }
    ]
  }
};
export default Portrait_Bokeh;
