const Portrait_Retro: Record<string, any> = {
  Classic_Fedora: {
    environment_title: "Classic_Fedora",
    images: [
      {
        original_file_name: "Classic_Fedora (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41178,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d5bba3",
        secondary: "#2a2214",
        tertiary: "#917058",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Classic_Fedora (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41989,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d3c3ac",
        secondary: "#282116",
        tertiary: "#887357",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Classic_Fedora (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43042,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cfc0b0",
        secondary: "#252219",
        tertiary: "#91aeb0",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Classic_Fedora (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43420,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbcab4",
        secondary: "#241511",
        tertiary: "#8e7b58",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Classic_Fedora (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7565340,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#d5bba3",
        secondary: "#2a2215",
        tertiary: "#917058",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Classic_Fedora (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7728153,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#d2c2ab",
        secondary: "#282116",
        tertiary: "#887356",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Classic_Fedora (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7528030,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#cfc0af",
        secondary: "#252219",
        tertiary: "#91afb0",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Classic_Fedora (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8221294,
        file_size_megabytes: 7.84,
        width: 3072,
        height: 5472,
        primary: "#dbcab4",
        secondary: "#241611",
        tertiary: "#8e7b58",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Dapper_Gentleman: {
    environment_title: "Dapper_Gentleman",
    images: [
      {
        original_file_name: "Dapper_Gentleman (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41466,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cba783",
        secondary: "#2f1e13",
        tertiary: "#906e4d",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Dapper_Gentleman (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44596,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d0a884",
        secondary: "#20120e",
        tertiary: "#805a41",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Dapper_Gentleman (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46629,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cea480",
        secondary: "#22140c",
        tertiary: "#836349",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Dapper_Gentleman (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42431,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e0c5a5",
        secondary: "#1e1714",
        tertiary: "#839e9c",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Dapper_Gentleman (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7953426,
        file_size_megabytes: 7.58,
        width: 3072,
        height: 5472,
        primary: "#cba783",
        secondary: "#2f1e12",
        tertiary: "#906e4d",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Dapper_Gentleman (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8997520,
        file_size_megabytes: 8.58,
        width: 3072,
        height: 5472,
        primary: "#d0a782",
        secondary: "#20120e",
        tertiary: "#805940",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Dapper_Gentleman (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9308260,
        file_size_megabytes: 8.88,
        width: 3072,
        height: 5472,
        primary: "#cea47f",
        secondary: "#22140c",
        tertiary: "#836348",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Dapper_Gentleman (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8042021,
        file_size_megabytes: 7.67,
        width: 3072,
        height: 5472,
        primary: "#e0c5a4",
        secondary: "#1e1714",
        tertiary: "#839d9b",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  OldHollywood_Starlet: {
    environment_title: "OldHollywood_Starlet",
    images: [
      {
        original_file_name: "OldHollywood_Starlet (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34472,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d8a379",
        secondary: "#281009",
        tertiary: "#6e3519",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "OldHollywood_Starlet (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42375,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#caa36d",
        secondary: "#2a1308",
        tertiary: "#633215",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "OldHollywood_Starlet (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38114,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1b110e",
        secondary: "#ddaf7b",
        tertiary: "#613318",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "OldHollywood_Starlet (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33423,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#bb8b68",
        secondary: "#f9d2a7",
        tertiary: "#25110a",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "OldHollywood_Starlet (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7935489,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#d8a378",
        secondary: "#271008",
        tertiary: "#6e3419",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "OldHollywood_Starlet (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7835834,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#caa36d",
        secondary: "#291307",
        tertiary: "#633214",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "OldHollywood_Starlet (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7297303,
        file_size_megabytes: 6.96,
        width: 3072,
        height: 5472,
        primary: "#1b100d",
        secondary: "#ddae7a",
        tertiary: "#613317",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "OldHollywood_Starlet (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7449553,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#bb8b67",
        secondary: "#f9d2a7",
        tertiary: "#25110a",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Retro_School_Portrait: {
    environment_title: "Retro_School_Portrait",
    images: [
      {
        original_file_name: "Retro_School_Portrait (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46414,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bc9a65",
        secondary: "#17171b",
        tertiary: "#552f18",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Retro_School_Portrait (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49127,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#b0976a",
        secondary: "#20191a",
        tertiary: "#633417",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Retro_School_Portrait (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45419,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d2aa75",
        secondary: "#83623a",
        tertiary: "#1b150f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Retro_School_Portrait (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41559,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#87653e",
        secondary: "#221917",
        tertiary: "#d5ae78",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Retro_School_Portrait (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9173195,
        file_size_megabytes: 8.75,
        width: 3072,
        height: 5472,
        primary: "#bc9a64",
        secondary: "#16171b",
        tertiary: "#552f18",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Retro_School_Portrait (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9238857,
        file_size_megabytes: 8.81,
        width: 3072,
        height: 5472,
        primary: "#b0986a",
        secondary: "#1f191a",
        tertiary: "#633316",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Retro_School_Portrait (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9211908,
        file_size_megabytes: 8.79,
        width: 3072,
        height: 5472,
        primary: "#d2a975",
        secondary: "#836239",
        tertiary: "#1b150f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Retro_School_Portrait (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8547857,
        file_size_megabytes: 8.15,
        width: 3072,
        height: 5472,
        primary: "#87643c",
        secondary: "#221917",
        tertiary: "#d5ae78",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Rustic_Charm: {
    environment_title: "Rustic_Charm",
    images: [
      {
        original_file_name: "Rustic_Charm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45985,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d7b889",
        secondary: "#27251f",
        tertiary: "#8a6b43",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46682,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d4ae7e",
        secondary: "#2e2922",
        tertiary: "#92af98",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47816,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dabc97",
        secondary: "#342d22",
        tertiary: "#8b704f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46034,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d3a77a",
        secondary: "#27281d",
        tertiary: "#886c44",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Rustic_Charm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8517483,
        file_size_megabytes: 8.12,
        width: 3072,
        height: 5472,
        primary: "#d8b989",
        secondary: "#27251f",
        tertiary: "#8a6b43",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8962163,
        file_size_megabytes: 8.55,
        width: 3072,
        height: 5472,
        primary: "#d4ae7d",
        secondary: "#2e2922",
        tertiary: "#92ae98",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8458842,
        file_size_megabytes: 8.07,
        width: 3072,
        height: 5472,
        primary: "#dbbd97",
        secondary: "#342d22",
        tertiary: "#8c704f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Rustic_Charm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8597833,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#d3a779",
        secondary: "#27281d",
        tertiary: "#886d44",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Sepia_Serenade: {
    environment_title: "Sepia_Serenade",
    images: [
      {
        original_file_name: "Sepia_Serenade (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35328,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#604228",
        secondary: "#d8b58d",
        tertiary: "#1e0e06",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Sepia_Serenade (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35337,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#a98258",
        secondary: "#5e3016",
        tertiary: "#231009",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Sepia_Serenade (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36846,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#debb98",
        secondary: "#50331e",
        tertiary: "#946a49",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Sepia_Serenade (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36253,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#dfc09b",
        secondary: "#654a30",
        tertiary: "#180d07",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Sepia_Serenade (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7750655,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#604228",
        secondary: "#d8b58d",
        tertiary: "#1e0e06",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Sepia_Serenade (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7222396,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#a98257",
        secondary: "#5f3015",
        tertiary: "#231008",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Sepia_Serenade (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7518999,
        file_size_megabytes: 7.17,
        width: 3072,
        height: 5472,
        primary: "#debb97",
        secondary: "#50341e",
        tertiary: "#946a48",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Sepia_Serenade (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7748798,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#dfc09b",
        secondary: "#684d33",
        tertiary: "#180d07",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Silent_Film_Actor: {
    environment_title: "Silent_Film_Actor",
    images: [
      {
        original_file_name: "Silent_Film_Actor (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29490,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#232321",
        secondary: "#c6c7c4",
        tertiary: "#787876",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Silent_Film_Actor (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31192,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#cececc",
        secondary: "#1b1b1a",
        tertiary: "#757572",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Silent_Film_Actor (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 30842,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#1d1d1b",
        secondary: "#cec9c2",
        tertiary: "#777570",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Silent_Film_Actor (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29429,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c7c7c5",
        secondary: "#0f0f0f",
        tertiary: "#676765",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Silent_Film_Actor (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7830352,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#232321",
        secondary: "#cbcbc8",
        tertiary: "#7b7b79",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Silent_Film_Actor (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7016642,
        file_size_megabytes: 6.69,
        width: 3072,
        height: 5472,
        primary: "#cececc",
        secondary: "#1b1b1a",
        tertiary: "#757572",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Silent_Film_Actor (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7448537,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#1d1d1b",
        secondary: "#cec9c2",
        tertiary: "#75736e",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Silent_Film_Actor (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6016793,
        file_size_megabytes: 5.74,
        width: 3072,
        height: 5472,
        primary: "#c4c4c2",
        secondary: "#0f0f0f",
        tertiary: "#6a6a69",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Timeless_Elegance: {
    environment_title: "Timeless_Elegance",
    images: [
      {
        original_file_name: "Timeless_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41293,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1d1914",
        secondary: "#795c3e",
        tertiary: "#f0cd9f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Timeless_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37823,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e2c4a6",
        secondary: "#59412c",
        tertiary: "#9b7758",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Timeless_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37020,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#18100c",
        secondary: "#ae9a7b",
        tertiary: "#647a69",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Timeless_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46767,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e1c2a9",
        secondary: "#301d16",
        tertiary: "#a2846c",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Timeless_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8366620,
        file_size_megabytes: 7.98,
        width: 3072,
        height: 5472,
        primary: "#1c1914",
        secondary: "#795c3e",
        tertiary: "#d9af81",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Timeless_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8029828,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#e2c3a6",
        secondary: "#59422c",
        tertiary: "#9c7758",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Timeless_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7619965,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#180f0b",
        secondary: "#a59477",
        tertiary: "#60331f",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Timeless_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8227804,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#e1c2a9",
        secondary: "#301d15",
        tertiary: "#a2846c",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Victorian_Elegance: {
    environment_title: "Victorian_Elegance",
    images: [
      {
        original_file_name: "Victorian_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45317,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e0c5a7",
        secondary: "#27120c",
        tertiary: "#906d4d",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Victorian_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48961,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d1ac87",
        secondary: "#2f1c11",
        tertiary: "#8f6748",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Victorian_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47053,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d9b48a",
        secondary: "#2a180f",
        tertiary: "#926c48",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Victorian_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53042,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ddc19e",
        secondary: "#29130e",
        tertiary: "#8f5b3e",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Victorian_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8020337,
        file_size_megabytes: 7.65,
        width: 3072,
        height: 5472,
        primary: "#e0c5a6",
        secondary: "#27120c",
        tertiary: "#906d4d",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Victorian_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8485076,
        file_size_megabytes: 8.09,
        width: 3072,
        height: 5472,
        primary: "#d6b08a",
        secondary: "#2f1c11",
        tertiary: "#926a4a",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Victorian_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8347027,
        file_size_megabytes: 7.96,
        width: 3072,
        height: 5472,
        primary: "#d9b48a",
        secondary: "#2a180e",
        tertiary: "#926b48",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Victorian_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8154543,
        file_size_megabytes: 7.78,
        width: 3072,
        height: 5472,
        primary: "#dec19e",
        secondary: "#29130d",
        tertiary: "#8e5b3c",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  },
  Vintage_Bride: {
    environment_title: "Vintage_Bride",
    images: [
      {
        original_file_name: "Vintage_Bride (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40465,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dbc0a2",
        secondary: "#342417",
        tertiary: "#9b7a5c",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Vintage_Bride (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42892,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d6bb9c",
        secondary: "#564323",
        tertiary: "#9e7955",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Vintage_Bride (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40673,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d8bea2",
        secondary: "#513a24",
        tertiary: "#95856a",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Vintage_Bride (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43143,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d6ba9b",
        secondary: "#382516",
        tertiary: "#947659",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "min"
      },
      {
        original_file_name: "Vintage_Bride (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7595285,
        file_size_megabytes: 7.24,
        width: 3072,
        height: 5472,
        primary: "#dbbfa0",
        secondary: "#342417",
        tertiary: "#9b7a5d",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Vintage_Bride (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8080354,
        file_size_megabytes: 7.71,
        width: 3072,
        height: 5472,
        primary: "#d6bb9b",
        secondary: "#564323",
        tertiary: "#9f7955",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Vintage_Bride (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7886594,
        file_size_megabytes: 7.52,
        width: 3072,
        height: 5472,
        primary: "#d8bda1",
        secondary: "#513a24",
        tertiary: "#95856a",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      },
      {
        original_file_name: "Vintage_Bride (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7912496,
        file_size_megabytes: 7.55,
        width: 3072,
        height: 5472,
        primary: "#d6ba9b",
        secondary: "#372516",
        tertiary: "#947658",
        Branch: "Portrait",
        FolderName: "Retro",
        Type: "max"
      }
    ]
  }
};
export default Portrait_Retro;
