const Anime_Illustration: Record<string, any> = {
  Busy_Market: {
    environment_title: "Busy_Market",
    images: [
      {
        original_file_name: "Busy_Market (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68494,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#e3be79",
        secondary: "#2e2230",
        tertiary: "#915740",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Busy_Market (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66810,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ebc997",
        secondary: "#322c32",
        tertiary: "#a05140",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Busy_Market (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72670,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#282e39",
        secondary: "#e0e293",
        tertiary: "#75453d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Busy_Market (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62496,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#eacba1",
        secondary: "#552c31",
        tertiary: "#a6b49e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Busy_Market (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7774081,
        file_size_megabytes: 7.41,
        width: 3072,
        height: 5472,
        primary: "#e5bd77",
        secondary: "#2e2230",
        tertiary: "#91573e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Busy_Market (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7261350,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#edca95",
        secondary: "#312c31",
        tertiary: "#a0503f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Busy_Market (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8291846,
        file_size_megabytes: 7.91,
        width: 3072,
        height: 5472,
        primary: "#272f3a",
        secondary: "#e1e392",
        tertiary: "#75443d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Busy_Market (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7235720,
        file_size_megabytes: 6.9,
        width: 3072,
        height: 5472,
        primary: "#ebcba0",
        secondary: "#552c31",
        tertiary: "#a5b49c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  City_Skyline: {
    environment_title: "City_Skyline",
    images: [
      {
        original_file_name: "City_Skyline (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58279,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d96561",
        secondary: "#23254a",
        tertiary: "#874e69",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "City_Skyline (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61239,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#9f3d42",
        secondary: "#1f1d36",
        tertiary: "#f6c466",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "City_Skyline (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48181,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d06568",
        secondary: "#1d192d",
        tertiary: "#624b6d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "City_Skyline (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58389,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e0665e",
        secondary: "#232249",
        tertiary: "#84455e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "City_Skyline (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6683407,
        file_size_megabytes: 6.37,
        width: 3072,
        height: 5472,
        primary: "#db6560",
        secondary: "#23254a",
        tertiary: "#874d69",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "City_Skyline (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7146627,
        file_size_megabytes: 6.82,
        width: 3072,
        height: 5472,
        primary: "#9e3d42",
        secondary: "#1e1e37",
        tertiary: "#f7c565",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "City_Skyline (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5687523,
        file_size_megabytes: 5.42,
        width: 3072,
        height: 5472,
        primary: "#d06568",
        secondary: "#1d192e",
        tertiary: "#624b6d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "City_Skyline (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6696566,
        file_size_megabytes: 6.39,
        width: 3072,
        height: 5472,
        primary: "#e2645d",
        secondary: "#232249",
        tertiary: "#84455d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Cozy_Bedroom: {
    environment_title: "Cozy_Bedroom",
    images: [
      {
        original_file_name: "Cozy_Bedroom (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40466,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#5f3c48",
        secondary: "#db663e",
        tertiary: "#21233a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Cozy_Bedroom (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42488,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#efbe9d",
        secondary: "#5a2f36",
        tertiary: "#9d4a44",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Cozy_Bedroom (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40883,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#f4edd2",
        secondary: "#6e3b40",
        tertiary: "#30273a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Cozy_Bedroom (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43371,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#edbb8d",
        secondary: "#5d3738",
        tertiary: "#231318",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Cozy_Bedroom (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4913111,
        file_size_megabytes: 4.69,
        width: 3072,
        height: 5472,
        primary: "#5f3c48",
        secondary: "#dd653d",
        tertiary: "#22233a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Cozy_Bedroom (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5217797,
        file_size_megabytes: 4.98,
        width: 3072,
        height: 5472,
        primary: "#f1be9d",
        secondary: "#5a2f36",
        tertiary: "#9d4943",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Cozy_Bedroom (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4938038,
        file_size_megabytes: 4.71,
        width: 3072,
        height: 5472,
        primary: "#f5edd3",
        secondary: "#703c41",
        tertiary: "#332a3c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Cozy_Bedroom (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5270850,
        file_size_megabytes: 5.03,
        width: 3072,
        height: 5472,
        primary: "#f0be8f",
        secondary: "#5e3739",
        tertiary: "#231418",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Golden_Wheat_Field: {
    environment_title: "Golden_Wheat_Field",
    images: [
      {
        original_file_name: "Golden_Wheat_Field (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 71464,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#2f3337",
        secondary: "#e09942",
        tertiary: "#83370a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Golden_Wheat_Field (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72479,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#39210d",
        secondary: "#753d10",
        tertiary: "#eab332",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Golden_Wheat_Field (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 69821,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#38260d",
        secondary: "#d17b26",
        tertiary: "#f8e652",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Golden_Wheat_Field (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 74406,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#342a0c",
        secondary: "#e0d8bc",
        tertiary: "#c2731a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Golden_Wheat_Field (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8367973,
        file_size_megabytes: 7.98,
        width: 3072,
        height: 5472,
        primary: "#2f3337",
        secondary: "#e39940",
        tertiary: "#833808",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Golden_Wheat_Field (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9035111,
        file_size_megabytes: 8.62,
        width: 3072,
        height: 5472,
        primary: "#39210d",
        secondary: "#753e0e",
        tertiary: "#edb32f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Golden_Wheat_Field (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8897176,
        file_size_megabytes: 8.49,
        width: 3072,
        height: 5472,
        primary: "#38270c",
        secondary: "#d67c20",
        tertiary: "#fae74f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Golden_Wheat_Field (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8965404,
        file_size_megabytes: 8.55,
        width: 3072,
        height: 5472,
        primary: "#392d0c",
        secondary: "#e1d9bc",
        tertiary: "#723a08",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Lonely_Train_Station: {
    environment_title: "Lonely_Train_Station",
    images: [
      {
        original_file_name: "Lonely_Train_Station (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50878,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d5c9bb",
        secondary: "#2f2f3e",
        tertiary: "#7e6562",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lonely_Train_Station (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51304,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d8d7d6",
        secondary: "#2b2c3c",
        tertiary: "#7b665d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lonely_Train_Station (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47991,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c49d9d",
        secondary: "#1d2842",
        tertiary: "#7aadef",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lonely_Train_Station (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46121,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d6b09f",
        secondary: "#262946",
        tertiary: "#78b1eb",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lonely_Train_Station (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6508665,
        file_size_megabytes: 6.21,
        width: 3072,
        height: 5472,
        primary: "#2f2f3e",
        secondary: "#d6c9bb",
        tertiary: "#7e6561",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lonely_Train_Station (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6502107,
        file_size_megabytes: 6.2,
        width: 3072,
        height: 5472,
        primary: "#d9d7d5",
        secondary: "#2b2c3c",
        tertiary: "#7c655c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lonely_Train_Station (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6639471,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#c49d9e",
        secondary: "#1d2842",
        tertiary: "#79acf1",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lonely_Train_Station (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6823154,
        file_size_megabytes: 6.51,
        width: 3072,
        height: 5472,
        primary: "#d7af9e",
        secondary: "#262a47",
        tertiary: "#78b1eb",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Lush_Green_Forest: {
    environment_title: "Lush_Green_Forest",
    images: [
      {
        original_file_name: "Lush_Green_Forest (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 85820,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#ccefa5",
        secondary: "#6cce92",
        tertiary: "#174c2e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lush_Green_Forest (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 87847,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#cdee9a",
        secondary: "#72d298",
        tertiary: "#1e502a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lush_Green_Forest (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 82813,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#62d6a6",
        secondary: "#ccf0aa",
        tertiary: "#184c2d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lush_Green_Forest (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 84073,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#c4f2c9",
        secondary: "#194e2c",
        tertiary: "#74cc82",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Lush_Green_Forest (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9105556,
        file_size_megabytes: 8.68,
        width: 3072,
        height: 5472,
        primary: "#cdf1a4",
        secondary: "#6bce90",
        tertiary: "#154c2e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lush_Green_Forest (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9315673,
        file_size_megabytes: 8.88,
        width: 3072,
        height: 5472,
        primary: "#ceef98",
        secondary: "#71d297",
        tertiary: "#1d502a",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lush_Green_Forest (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8622986,
        file_size_megabytes: 8.22,
        width: 3072,
        height: 5472,
        primary: "#60d7a5",
        secondary: "#cef1aa",
        tertiary: "#174c2d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Lush_Green_Forest (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8752220,
        file_size_megabytes: 8.35,
        width: 3072,
        height: 5472,
        primary: "#c5f3c9",
        secondary: "#184e2c",
        tertiary: "#73cc7f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Minimalist_Garden: {
    environment_title: "Minimalist_Garden",
    images: [
      {
        original_file_name: "Minimalist_Garden (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70102,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#88dc3a",
        secondary: "#e5eebf",
        tertiary: "#184e2d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Minimalist_Garden (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72973,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#cdee7c",
        secondary: "#125a2d",
        tertiary: "#80d444",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Minimalist_Garden (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70485,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d1ec99",
        secondary: "#133622",
        tertiary: "#85c45c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Minimalist_Garden (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 78151,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d4e598",
        secondary: "#185030",
        tertiary: "#8bd464",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Minimalist_Garden (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7723961,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#84db36",
        secondary: "#e0edb5",
        tertiary: "#164e2d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Minimalist_Garden (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8366375,
        file_size_megabytes: 7.98,
        width: 3072,
        height: 5472,
        primary: "#ceef7b",
        secondary: "#115a2d",
        tertiary: "#80d541",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Minimalist_Garden (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8125431,
        file_size_megabytes: 7.75,
        width: 3072,
        height: 5472,
        primary: "#d2ec98",
        secondary: "#123622",
        tertiary: "#84c559",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Minimalist_Garden (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8516548,
        file_size_megabytes: 8.12,
        width: 3072,
        height: 5472,
        primary: "#d4e697",
        secondary: "#175030",
        tertiary: "#8ad462",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Ocean_Waves: {
    environment_title: "Ocean_Waves",
    images: [
      {
        original_file_name: "Ocean_Waves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57653,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c07a69",
        secondary: "#255978",
        tertiary: "#adb8d7",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Ocean_Waves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62332,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#244e78",
        secondary: "#eedfab",
        tertiary: "#6f5a6c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Ocean_Waves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 60770,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#1f6778",
        secondary: "#c57d64",
        tertiary: "#b3cae4",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Ocean_Waves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63969,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#2f5c91",
        secondary: "#cc836a",
        tertiary: "#c1cedc",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Ocean_Waves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7488970,
        file_size_megabytes: 7.14,
        width: 3072,
        height: 5472,
        primary: "#c07969",
        secondary: "#255978",
        tertiary: "#acb8d7",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Ocean_Waves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7913846,
        file_size_megabytes: 7.55,
        width: 3072,
        height: 5472,
        primary: "#244f79",
        secondary: "#efdfab",
        tertiary: "#6f596c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Ocean_Waves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7761733,
        file_size_megabytes: 7.4,
        width: 3072,
        height: 5472,
        primary: "#1e6879",
        secondary: "#c67c64",
        tertiary: "#b3cae5",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Ocean_Waves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7777466,
        file_size_megabytes: 7.42,
        width: 3072,
        height: 5472,
        primary: "#2f619f",
        secondary: "#cf856a",
        tertiary: "#c1cfdd",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Quiet_Alleyway: {
    environment_title: "Quiet_Alleyway",
    images: [
      {
        original_file_name: "Quiet_Alleyway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49377,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d18e82",
        secondary: "#192341",
        tertiary: "#3663b6",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Alleyway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50156,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#1a1c31",
        secondary: "#be625e",
        tertiary: "#3575cc",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Alleyway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51016,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c67562",
        secondary: "#1d243f",
        tertiary: "#364b7f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Alleyway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50897,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d38b6a",
        secondary: "#211f30",
        tertiary: "#7a4d4d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Alleyway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6867359,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#d18c81",
        secondary: "#192341",
        tertiary: "#3463b7",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Alleyway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6862774,
        file_size_megabytes: 6.54,
        width: 3072,
        height: 5472,
        primary: "#191c31",
        secondary: "#bf625d",
        tertiary: "#3475cd",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Alleyway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6549367,
        file_size_megabytes: 6.25,
        width: 3072,
        height: 5472,
        primary: "#c87461",
        secondary: "#1d253f",
        tertiary: "#374b7f",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Alleyway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6858013,
        file_size_megabytes: 6.54,
        width: 3072,
        height: 5472,
        primary: "#d48b6a",
        secondary: "#212030",
        tertiary: "#7a4945",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Quiet_Caf_Scene: {
    environment_title: "Quiet_Caf_Scene",
    images: [
      {
        original_file_name: "Quiet_Caf_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48656,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#edc181",
        secondary: "#3c2619",
        tertiary: "#9d5b34",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Caf_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51726,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e3b678",
        secondary: "#2e1d1c",
        tertiary: "#915033",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Caf_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56548,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e3c197",
        secondary: "#4e2d22",
        tertiary: "#955e40",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Caf_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50092,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e6cb95",
        secondary: "#4d2f24",
        tertiary: "#956143",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Quiet_Caf_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5984397,
        file_size_megabytes: 5.71,
        width: 3072,
        height: 5472,
        primary: "#edbe7e",
        secondary: "#3c2619",
        tertiary: "#9d5a33",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Caf_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6205428,
        file_size_megabytes: 5.92,
        width: 3072,
        height: 5472,
        primary: "#e4b274",
        secondary: "#2e1d1c",
        tertiary: "#914f32",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Caf_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6426297,
        file_size_megabytes: 6.13,
        width: 3072,
        height: 5472,
        primary: "#e4c195",
        secondary: "#4e2d22",
        tertiary: "#955c3d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Quiet_Caf_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6021718,
        file_size_megabytes: 5.74,
        width: 3072,
        height: 5472,
        primary: "#eace96",
        secondary: "#4f3024",
        tertiary: "#9c6645",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Rainbow_Umbrella_Street: {
    environment_title: "Rainbow_Umbrella_Street",
    images: [
      {
        original_file_name: "Rainbow_Umbrella_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 67331,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#1e2b3d",
        secondary: "#cf8b78",
        tertiary: "#d7e6e4",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61350,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e4c9a0",
        secondary: "#453f56",
        tertiary: "#81d6c0",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62566,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e9b58e",
        secondary: "#5fd2c4",
        tertiary: "#302f3d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66647,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e4b08b",
        secondary: "#60dabc",
        tertiary: "#272238",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7623010,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#edc590",
        secondary: "#63d5c3",
        tertiary: "#272938",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7127566,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#e5c99f",
        secondary: "#453e56",
        tertiary: "#81d6c1",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7515522,
        file_size_megabytes: 7.17,
        width: 3072,
        height: 5472,
        primary: "#eab58d",
        secondary: "#5dd3c6",
        tertiary: "#302f3d",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Rainbow_Umbrella_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8033311,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#e6b08b",
        secondary: "#5edcbb",
        tertiary: "#262238",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Serene_Lakeside: {
    environment_title: "Serene_Lakeside",
    images: [
      {
        original_file_name: "Serene_Lakeside (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76632,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#cce8da",
        secondary: "#2b8fdd",
        tertiary: "#6cd1d9",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Serene_Lakeside (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70966,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d6e7e2",
        secondary: "#2c678b",
        tertiary: "#6cd2eb",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Serene_Lakeside (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 69166,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d3e2d5",
        secondary: "#3992cc",
        tertiary: "#103043",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Serene_Lakeside (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76355,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#cde7cd",
        secondary: "#1c4962",
        tertiary: "#2997e5",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Serene_Lakeside (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8209008,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#cce8db",
        secondary: "#2a8ede",
        tertiary: "#6bd1d9",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Serene_Lakeside (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7933391,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#d7e7e2",
        secondary: "#2b678b",
        tertiary: "#6ad2ec",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Serene_Lakeside (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7638643,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#d3e2d4",
        secondary: "#3891cd",
        tertiary: "#103043",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Serene_Lakeside (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8309374,
        file_size_megabytes: 7.92,
        width: 3072,
        height: 5472,
        primary: "#cde8cc",
        secondary: "#1b4962",
        tertiary: "#2897e7",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Summer_Festival: {
    environment_title: "Summer_Festival",
    images: [
      {
        original_file_name: "Summer_Festival (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62840,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#efaa64",
        secondary: "#1d1826",
        tertiary: "#9f412e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Summer_Festival (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62289,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#f4d782",
        secondary: "#1f1921",
        tertiary: "#693127",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Summer_Festival (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57842,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ea9c5e",
        secondary: "#271f29",
        tertiary: "#994737",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Summer_Festival (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61612,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#eba561",
        secondary: "#913b31",
        tertiary: "#141c3b",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Summer_Festival (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6623954,
        file_size_megabytes: 6.32,
        width: 3072,
        height: 5472,
        primary: "#f1aa63",
        secondary: "#1c1927",
        tertiary: "#9f402c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Summer_Festival (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7168376,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#f6d881",
        secondary: "#1f1922",
        tertiary: "#683126",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Summer_Festival (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6482603,
        file_size_megabytes: 6.18,
        width: 3072,
        height: 5472,
        primary: "#ec9c5c",
        secondary: "#261f29",
        tertiary: "#994637",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Summer_Festival (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6361564,
        file_size_megabytes: 6.07,
        width: 3072,
        height: 5472,
        primary: "#eda560",
        secondary: "#913a30",
        tertiary: "#141d3b",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Sunrise_Over_Hills: {
    environment_title: "Sunrise_Over_Hills",
    images: [
      {
        original_file_name: "Sunrise_Over_Hills (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47843,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e9cd90",
        secondary: "#3b595f",
        tertiary: "#9bc03e",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Sunrise_Over_Hills (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54783,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e5b493",
        secondary: "#5984c6",
        tertiary: "#2a4834",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Sunrise_Over_Hills (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48337,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e9d2b3",
        secondary: "#2b4b3d",
        tertiary: "#e1df38",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Sunrise_Over_Hills (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48538,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e4b9a3",
        secondary: "#2e5538",
        tertiary: "#6f95da",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Sunrise_Over_Hills (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6446731,
        file_size_megabytes: 6.15,
        width: 3072,
        height: 5472,
        primary: "#eacd90",
        secondary: "#3b595f",
        tertiary: "#9ac03c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Sunrise_Over_Hills (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7603181,
        file_size_megabytes: 7.25,
        width: 3072,
        height: 5472,
        primary: "#e7b493",
        secondary: "#5984c6",
        tertiary: "#2a4834",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Sunrise_Over_Hills (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6724435,
        file_size_megabytes: 6.41,
        width: 3072,
        height: 5472,
        primary: "#ead3b1",
        secondary: "#2b4b3e",
        tertiary: "#7f845b",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Sunrise_Over_Hills (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7320433,
        file_size_megabytes: 6.98,
        width: 3072,
        height: 5472,
        primary: "#e6b9a8",
        secondary: "#2e5538",
        tertiary: "#759de1",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  },
  Urban_Crosswalk: {
    environment_title: "Urban_Crosswalk",
    images: [
      {
        original_file_name: "Urban_Crosswalk (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50612,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d7a3a2",
        secondary: "#1b2036",
        tertiary: "#456ccc",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Urban_Crosswalk (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52686,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d4b293",
        secondary: "#1e2f3f",
        tertiary: "#61bb9c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Urban_Crosswalk (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62308,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ded3be",
        secondary: "#283650",
        tertiary: "#937d70",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Urban_Crosswalk (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51537,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#daba90",
        secondary: "#222a4c",
        tertiary: "#69b1aa",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "min"
      },
      {
        original_file_name: "Urban_Crosswalk (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6537601,
        file_size_megabytes: 6.23,
        width: 3072,
        height: 5472,
        primary: "#d9a4a1",
        secondary: "#1b2036",
        tertiary: "#446bcd",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Urban_Crosswalk (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6110547,
        file_size_megabytes: 5.83,
        width: 3072,
        height: 5472,
        primary: "#d5b292",
        secondary: "#1e303f",
        tertiary: "#5fbf9c",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Urban_Crosswalk (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6862850,
        file_size_megabytes: 6.54,
        width: 3072,
        height: 5472,
        primary: "#ded2bd",
        secondary: "#283650",
        tertiary: "#947c70",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      },
      {
        original_file_name: "Urban_Crosswalk (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6665918,
        file_size_megabytes: 6.36,
        width: 3072,
        height: 5472,
        primary: "#dcba8f",
        secondary: "#212a4c",
        tertiary: "#68b2ab",
        Branch: "Anime",
        FolderName: "Illustration",
        Type: "max"
      }
    ]
  }
};
export default Anime_Illustration;
