import { EnvironmentEntry } from "@/types/database";
const Anime_Background: Record<string, EnvironmentEntry> = {
  Bustling_City_Street: {
    environment_title: "Bustling_City_Street",
    images: [
      {
        original_file_name: "Bustling_City_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72711,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#e3d0b9",
        secondary: "#2b3f4f",
        tertiary: "#8ecfd6",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Bustling_City_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66564,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ded1b0",
        secondary: "#22354e",
        tertiary: "#58c7dc",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Bustling_City_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72622,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#eadcb6",
        secondary: "#293647",
        tertiary: "#7ec7c5",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Bustling_City_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 65969,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e4dcc7",
        secondary: "#283f50",
        tertiary: "#7fd1cf",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Bustling_City_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8359502,
        file_size_megabytes: 7.97,
        width: 3072,
        height: 5472,
        primary: "#e4d0b8",
        secondary: "#2a3f4f",
        tertiary: "#8ed0d7",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Bustling_City_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7871931,
        file_size_megabytes: 7.51,
        width: 3072,
        height: 5472,
        primary: "#e0d1af",
        secondary: "#22354f",
        tertiary: "#55c8de",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Bustling_City_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8122372,
        file_size_megabytes: 7.75,
        width: 3072,
        height: 5472,
        primary: "#ecdcb5",
        secondary: "#323d51",
        tertiary: "#7dc7c6",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Bustling_City_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7845212,
        file_size_megabytes: 7.48,
        width: 3072,
        height: 5472,
        primary: "#e5dcc6",
        secondary: "#273f50",
        tertiary: "#7dd2d0",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Dramatic_Cliffside: {
    environment_title: "Dramatic_Cliffside",
    images: [
      {
        original_file_name: "Dramatic_Cliffside (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63769,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c4ebbd",
        secondary: "#0c3d50",
        tertiary: "#64d3b2",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Dramatic_Cliffside (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 60768,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c4e6c8",
        secondary: "#69ccac",
        tertiary: "#114054",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Dramatic_Cliffside (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58894,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#cee6d7",
        secondary: "#72cbbc",
        tertiary: "#0d5a7d",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Dramatic_Cliffside (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57504,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c7e4d6",
        secondary: "#10606c",
        tertiary: "#2985da",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Dramatic_Cliffside (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7657768,
        file_size_megabytes: 7.3,
        width: 3072,
        height: 5472,
        primary: "#c0eab8",
        secondary: "#0b3d50",
        tertiary: "#5bd1bb",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Dramatic_Cliffside (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7527082,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#c5e6c9",
        secondary: "#69ccac",
        tertiary: "#104054",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Dramatic_Cliffside (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7000643,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#cfe6d8",
        secondary: "#71cbbd",
        tertiary: "#0c597b",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Dramatic_Cliffside (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7045531,
        file_size_megabytes: 6.72,
        width: 3072,
        height: 5472,
        primary: "#c7e5d6",
        secondary: "#0e5a67",
        tertiary: "#2885db",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Festive_Market_Street: {
    environment_title: "Festive_Market_Street",
    images: [
      {
        original_file_name: "Festive_Market_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72058,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#e7c996",
        secondary: "#48353e",
        tertiary: "#88c8c5",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Festive_Market_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64697,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e3ac6e",
        secondary: "#201d33",
        tertiary: "#824b39",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Festive_Market_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63267,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e2b275",
        secondary: "#322e48",
        tertiary: "#895347",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Festive_Market_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 65976,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e2be8b",
        secondary: "#282635",
        tertiary: "#884f3f",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Festive_Market_Street (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8756162,
        file_size_megabytes: 8.35,
        width: 3072,
        height: 5472,
        primary: "#e9c995",
        secondary: "#372f40",
        tertiary: "#87cac8",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Festive_Market_Street (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7694185,
        file_size_megabytes: 7.34,
        width: 3072,
        height: 5472,
        primary: "#e6ac6d",
        secondary: "#201e33",
        tertiary: "#814937",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Festive_Market_Street (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7621936,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#e4b174",
        secondary: "#322e48",
        tertiary: "#895246",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Festive_Market_Street (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7997085,
        file_size_megabytes: 7.63,
        width: 3072,
        height: 5472,
        primary: "#e4be8b",
        secondary: "#282636",
        tertiary: "#884d3e",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Forest_Clearing: {
    environment_title: "Forest_Clearing",
    images: [
      {
        original_file_name: "Forest_Clearing (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 73038,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#bce4a5",
        secondary: "#15322b",
        tertiary: "#73c18c",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Forest_Clearing (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70141,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#c6eabc",
        secondary: "#65c6af",
        tertiary: "#11332f",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Forest_Clearing (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 75126,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#c5e6aa",
        secondary: "#67cea2",
        tertiary: "#112d27",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Forest_Clearing (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76376,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#bfe6b2",
        secondary: "#184c39",
        tertiary: "#72caa1",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Forest_Clearing (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9003339,
        file_size_megabytes: 8.59,
        width: 3072,
        height: 5472,
        primary: "#bde5a4",
        secondary: "#15322b",
        tertiary: "#72c28b",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Forest_Clearing (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8586036,
        file_size_megabytes: 8.19,
        width: 3072,
        height: 5472,
        primary: "#c8ebbc",
        secondary: "#65c7ae",
        tertiary: "#11322f",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Forest_Clearing (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9070268,
        file_size_megabytes: 8.65,
        width: 3072,
        height: 5472,
        primary: "#c6e7a9",
        secondary: "#66cfa2",
        tertiary: "#102e27",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Forest_Clearing (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8920030,
        file_size_megabytes: 8.51,
        width: 3072,
        height: 5472,
        primary: "#c0e8b2",
        secondary: "#184c39",
        tertiary: "#71cba0",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Hidden_Waterfall: {
    environment_title: "Hidden_Waterfall",
    images: [
      {
        original_file_name: "Hidden_Waterfall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52819,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#4cbeec",
        secondary: "#227cdd",
        tertiary: "#061d2f",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Hidden_Waterfall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56668,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c6b690",
        secondary: "#43b5d8",
        tertiary: "#0c1f29",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Hidden_Waterfall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50087,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#092c40",
        secondary: "#3dc9e1",
        tertiary: "#2185c6",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Hidden_Waterfall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55928,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#071b2d",
        secondary: "#34c4e9",
        tertiary: "#207dc1",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Hidden_Waterfall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6585630,
        file_size_megabytes: 6.28,
        width: 3072,
        height: 5472,
        primary: "#49bdee",
        secondary: "#217bdf",
        tertiary: "#061c2f",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Hidden_Waterfall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7635718,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#c7b58f",
        secondary: "#41b6d9",
        tertiary: "#0c1f29",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Hidden_Waterfall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6977956,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#082c40",
        secondary: "#3bc9e3",
        tertiary: "#1e83c5",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Hidden_Waterfall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7132203,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#061b2d",
        secondary: "#33c5ea",
        tertiary: "#1e7dc2",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Lush_Rice_Fields: {
    environment_title: "Lush_Rice_Fields",
    images: [
      {
        original_file_name: "Lush_Rice_Fields (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 65045,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#3697d1",
        secondary: "#d5ebdb",
        tertiary: "#7ae03c",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Lush_Rice_Fields (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62406,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#50b1dd",
        secondary: "#173022",
        tertiary: "#c9e8b8",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Lush_Rice_Fields (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68528,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d5dfbf",
        secondary: "#59ab2f",
        tertiary: "#16371d",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Lush_Rice_Fields (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68400,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#0e2d1e",
        secondary: "#cbde8e",
        tertiary: "#327328",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Lush_Rice_Fields (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8663253,
        file_size_megabytes: 8.26,
        width: 3072,
        height: 5472,
        primary: "#3596d3",
        secondary: "#d6ecdb",
        tertiary: "#28692d",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Lush_Rice_Fields (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9144881,
        file_size_megabytes: 8.72,
        width: 3072,
        height: 5472,
        primary: "#4fb1de",
        secondary: "#173022",
        tertiary: "#c9e9b8",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Lush_Rice_Fields (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9126688,
        file_size_megabytes: 8.7,
        width: 3072,
        height: 5472,
        primary: "#d5dfbf",
        secondary: "#5baf2f",
        tertiary: "#16371c",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Lush_Rice_Fields (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9308958,
        file_size_megabytes: 8.88,
        width: 3072,
        height: 5472,
        primary: "#0c2e1e",
        secondary: "#ccde8f",
        tertiary: "#307226",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Peaceful_Shrine: {
    environment_title: "Peaceful_Shrine",
    images: [
      {
        original_file_name: "Peaceful_Shrine (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54925,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#0e2934",
        secondary: "#50cbd0",
        tertiary: "#beb39e",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Peaceful_Shrine (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56014,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#16313f",
        secondary: "#bb9169",
        tertiary: "#1c6b82",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Peaceful_Shrine (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58742,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#152d33",
        secondary: "#d0c9ac",
        tertiary: "#62bfa1",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Peaceful_Shrine (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68453,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#c8d69e",
        secondary: "#7bc8a8",
        tertiary: "#1d302a",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Peaceful_Shrine (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7401397,
        file_size_megabytes: 7.06,
        width: 3072,
        height: 5472,
        primary: "#0d2934",
        secondary: "#4ecbd1",
        tertiary: "#c1b19b",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Peaceful_Shrine (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7442191,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#15313f",
        secondary: "#bd9067",
        tertiary: "#1a6a82",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Peaceful_Shrine (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7381509,
        file_size_megabytes: 7.04,
        width: 3072,
        height: 5472,
        primary: "#152d33",
        secondary: "#d3c9aa",
        tertiary: "#60c1a1",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Peaceful_Shrine (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8282277,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#c9d69c",
        secondary: "#7ac9a8",
        tertiary: "#1d302a",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Quiet_Classroom: {
    environment_title: "Quiet_Classroom",
    images: [
      {
        original_file_name: "Quiet_Classroom (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50107,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#6c5a4a",
        secondary: "#e1e7c7",
        tertiary: "#30393c",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Classroom (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54435,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e0e1bf",
        secondary: "#323d46",
        tertiary: "#8dcfd1",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Classroom (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51131,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#4d4541",
        secondary: "#e4e3cd",
        tertiary: "#a1cdd4",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Classroom (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47437,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e4ddb1",
        secondary: "#383f45",
        tertiary: "#957a63",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Classroom (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6168445,
        file_size_megabytes: 5.88,
        width: 3072,
        height: 5472,
        primary: "#6c5a4a",
        secondary: "#e1e7c6",
        tertiary: "#30393c",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Classroom (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6497350,
        file_size_megabytes: 6.2,
        width: 3072,
        height: 5472,
        primary: "#e1e1be",
        secondary: "#323d47",
        tertiary: "#8dcfd3",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Classroom (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6190483,
        file_size_megabytes: 5.9,
        width: 3072,
        height: 5472,
        primary: "#e5e2cc",
        secondary: "#4d4541",
        tertiary: "#a1cdd5",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Classroom (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5871164,
        file_size_megabytes: 5.6,
        width: 3072,
        height: 5472,
        primary: "#e5ddaf",
        secondary: "#383f45",
        tertiary: "#957a62",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Quiet_Library: {
    environment_title: "Quiet_Library",
    images: [
      {
        original_file_name: "Quiet_Library (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52935,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e1b471",
        secondary: "#46291c",
        tertiary: "#8e5a32",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Library (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52515,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d7a86f",
        secondary: "#2d1d1d",
        tertiary: "#6fc0ee",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Library (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50924,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e0b896",
        secondary: "#312123",
        tertiary: "#805840",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Library (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53998,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dbac7a",
        secondary: "#3e241c",
        tertiary: "#844d32",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Quiet_Library (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6997619,
        file_size_megabytes: 6.67,
        width: 3072,
        height: 5472,
        primary: "#e2b46f",
        secondary: "#46291c",
        tertiary: "#8d5831",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Library (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7017968,
        file_size_megabytes: 6.69,
        width: 3072,
        height: 5472,
        primary: "#d9a76c",
        secondary: "#2d1d1d",
        tertiary: "#6ec0f0",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Library (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6413809,
        file_size_megabytes: 6.12,
        width: 3072,
        height: 5472,
        primary: "#e1b895",
        secondary: "#312223",
        tertiary: "#7f563e",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Quiet_Library (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7193415,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#dbaa77",
        secondary: "#3e241c",
        tertiary: "#844d32",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Rainy_Alleyway: {
    environment_title: "Rainy_Alleyway",
    images: [
      {
        original_file_name: "Rainy_Alleyway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57979,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#caafab",
        secondary: "#111a2e",
        tertiary: "#54c5e4",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rainy_Alleyway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56630,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ce9278",
        secondary: "#151a31",
        tertiary: "#44b8e7",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rainy_Alleyway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59599,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d59e78",
        secondary: "#17192a",
        tertiary: "#56b3e5",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rainy_Alleyway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 60131,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d09c94",
        secondary: "#0f152a",
        tertiary: "#3ac5e7",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rainy_Alleyway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7592293,
        file_size_megabytes: 7.24,
        width: 3072,
        height: 5472,
        primary: "#cdb3af",
        secondary: "#111a2e",
        tertiary: "#51c6e7",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rainy_Alleyway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7639029,
        file_size_megabytes: 7.29,
        width: 3072,
        height: 5472,
        primary: "#d09176",
        secondary: "#151a31",
        tertiary: "#43baeb",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rainy_Alleyway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7749659,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#d69a73",
        secondary: "#17192a",
        tertiary: "#55b5e9",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rainy_Alleyway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7922823,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#d29c93",
        secondary: "#0f152a",
        tertiary: "#35c7ea",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Rooftop_Hangout: {
    environment_title: "Rooftop_Hangout",
    images: [
      {
        original_file_name: "Rooftop_Hangout (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 65985,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d7d2c0",
        secondary: "#142932",
        tertiary: "#5fc3d7",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rooftop_Hangout (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64323,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e2d4a7",
        secondary: "#204a3c",
        tertiary: "#5085c7",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rooftop_Hangout (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59187,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d5b492",
        secondary: "#20394e",
        tertiary: "#6bacaf",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rooftop_Hangout (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63444,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d2c9ac",
        secondary: "#3c8bc6",
        tertiary: "#172733",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Rooftop_Hangout (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8080447,
        file_size_megabytes: 7.71,
        width: 3072,
        height: 5472,
        primary: "#d8d2be",
        secondary: "#132932",
        tertiary: "#5ec3d9",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rooftop_Hangout (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8034975,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#e4d5a6",
        secondary: "#1d442b",
        tertiary: "#446a9e",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rooftop_Hangout (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7681929,
        file_size_megabytes: 7.33,
        width: 3072,
        height: 5472,
        primary: "#d6b491",
        secondary: "#1f394e",
        tertiary: "#6bacaf",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Rooftop_Hangout (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7602840,
        file_size_megabytes: 7.25,
        width: 3072,
        height: 5472,
        primary: "#d3c9ab",
        secondary: "#3a8bc6",
        tertiary: "#172733",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Starry_Night_Field: {
    environment_title: "Starry_Night_Field",
    images: [
      {
        original_file_name: "Starry_Night_Field (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52654,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#0e2f60",
        secondary: "#d2c0b3",
        tertiary: "#1477d5",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Starry_Night_Field (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51685,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d3b99b",
        secondary: "#0d2d39",
        tertiary: "#1270d4",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Starry_Night_Field (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56316,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#0c315d",
        secondary: "#d0c6bf",
        tertiary: "#1276d7",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Starry_Night_Field (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53394,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d0b5be",
        secondary: "#0b3266",
        tertiary: "#082322",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Starry_Night_Field (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7509372,
        file_size_megabytes: 7.16,
        width: 3072,
        height: 5472,
        primary: "#0d2f60",
        secondary: "#d3c0b2",
        tertiary: "#1377d6",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Starry_Night_Field (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7658449,
        file_size_megabytes: 7.3,
        width: 3072,
        height: 5472,
        primary: "#d5b89b",
        secondary: "#0c2d39",
        tertiary: "#1170d5",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Starry_Night_Field (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7497192,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#0a315d",
        secondary: "#ccc3bf",
        tertiary: "#1076d8",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Starry_Night_Field (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7391505,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#0b3467",
        secondary: "#cdb3bd",
        tertiary: "#072322",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Sunlit_Hilltop: {
    environment_title: "Sunlit_Hilltop",
    images: [
      {
        original_file_name: "Sunlit_Hilltop (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 73519,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#1f3826",
        secondary: "#6eb4e4",
        tertiary: "#ddccc8",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunlit_Hilltop (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66118,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d5d5d9",
        secondary: "#6eb9df",
        tertiary: "#17301e",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunlit_Hilltop (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 78589,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#ded6ce",
        secondary: "#28282e",
        tertiary: "#3e8235",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunlit_Hilltop (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66854,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#dbc8c6",
        secondary: "#1f3c27",
        tertiary: "#74c1e8",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunlit_Hilltop (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9212417,
        file_size_megabytes: 8.79,
        width: 3072,
        height: 5472,
        primary: "#1f3826",
        secondary: "#6db4e6",
        tertiary: "#deccc8",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunlit_Hilltop (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9192819,
        file_size_megabytes: 8.77,
        width: 3072,
        height: 5472,
        primary: "#d6d5da",
        secondary: "#6dbae1",
        tertiary: "#17301f",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunlit_Hilltop (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9372192,
        file_size_megabytes: 8.94,
        width: 3072,
        height: 5472,
        primary: "#e0d6ce",
        secondary: "#29272e",
        tertiary: "#3e8334",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunlit_Hilltop (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8636332,
        file_size_megabytes: 8.24,
        width: 3072,
        height: 5472,
        primary: "#ddc7c7",
        secondary: "#1f3c27",
        tertiary: "#73c1e9",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Sunset_Pier: {
    environment_title: "Sunset_Pier",
    images: [
      {
        original_file_name: "Sunset_Pier (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52876,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#eb9a60",
        secondary: "#32282e",
        tertiary: "#a45f56",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunset_Pier (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54400,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e9935f",
        secondary: "#512c2a",
        tertiary: "#a65b4e",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunset_Pier (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53143,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e79658",
        secondary: "#382022",
        tertiary: "#995749",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunset_Pier (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57816,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#f6d485",
        secondary: "#2f1c1d",
        tertiary: "#723e31",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Sunset_Pier (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6742537,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#ed9a5f",
        secondary: "#32282e",
        tertiary: "#a45f56",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunset_Pier (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7288191,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#ea935e",
        secondary: "#512c2a",
        tertiary: "#a65a4c",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunset_Pier (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6745851,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#e89557",
        secondary: "#382023",
        tertiary: "#9a574a",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Sunset_Pier (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7308543,
        file_size_megabytes: 6.97,
        width: 3072,
        height: 5472,
        primary: "#f7d584",
        secondary: "#2f1c1e",
        tertiary: "#723d30",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  },
  Traditional_Tea_House: {
    environment_title: "Traditional_Tea_House",
    images: [
      {
        original_file_name: "Traditional_Tea_House (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48141,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dfe197",
        secondary: "#45371f",
        tertiary: "#8eb764",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Traditional_Tea_House (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61526,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e6cf85",
        secondary: "#454027",
        tertiary: "#93bf5e",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Traditional_Tea_House (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50588,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dcdd9d",
        secondary: "#392f18",
        tertiary: "#93b25e",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Traditional_Tea_House (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51901,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d8d38e",
        secondary: "#333721",
        tertiary: "#888053",
        branch: "Anime",
        folder: "Background",
        type: "min"
      },
      {
        original_file_name: "Traditional_Tea_House (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5834217,
        file_size_megabytes: 5.56,
        width: 3072,
        height: 5472,
        primary: "#dfe096",
        secondary: "#45371f",
        tertiary: "#8eb763",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Traditional_Tea_House (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7447367,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#e7ce83",
        secondary: "#454027",
        tertiary: "#93bf5b",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Traditional_Tea_House (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6161763,
        file_size_megabytes: 5.88,
        width: 3072,
        height: 5472,
        primary: "#dddd9c",
        secondary: "#392f18",
        tertiary: "#94b35f",
        branch: "Anime",
        folder: "Background",
        type: "max"
      },
      {
        original_file_name: "Traditional_Tea_House (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6742829,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#d9d38d",
        secondary: "#333721",
        tertiary: "#888053",
        branch: "Anime",
        folder: "Background",
        type: "max"
      }
    ]
  }
};
export default Anime_Background;
