import { EnvironmentEntry } from "@/types/database";
const Anime_Manga: Record<string, EnvironmentEntry> = {
  Aerial_Battle: {
    environment_title: "Aerial_Battle",
    images: [
      {
        original_file_name: "Aerial_Battle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46058,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c4c4c4",
        secondary: "#616161",
        tertiary: "#888888",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Aerial_Battle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42939,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d2c1b8",
        secondary: "#1e1e1e",
        tertiary: "#908884",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Aerial_Battle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48469,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#181918",
        secondary: "#bebebe",
        tertiary: "#737372",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Aerial_Battle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49825,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#b7b7b7",
        secondary: "#060606",
        tertiary: "#5e5e5e",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Aerial_Battle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4067267,
        file_size_megabytes: 3.88,
        width: 3072,
        height: 5472,
        primary: "#c4c4c4",
        secondary: "#616161",
        tertiary: "#878787",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Aerial_Battle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4467816,
        file_size_megabytes: 4.26,
        width: 3072,
        height: 5472,
        primary: "#d2c1b8",
        secondary: "#1e1e1e",
        tertiary: "#908884",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Aerial_Battle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4499334,
        file_size_megabytes: 4.29,
        width: 3072,
        height: 5472,
        primary: "#181817",
        secondary: "#bebebe",
        tertiary: "#737371",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Aerial_Battle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3672511,
        file_size_megabytes: 3.5,
        width: 3072,
        height: 5472,
        primary: "#b5b5b5",
        secondary: "#060606",
        tertiary: "#848483",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Anguished_Shout: {
    environment_title: "Anguished_Shout",
    images: [
      {
        original_file_name: "Anguished_Shout (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 72733,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#1a1a1a",
        secondary: "#dadada",
        tertiary: "#787877",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Anguished_Shout (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63689,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#9b9b9a",
        secondary: "#171717",
        tertiary: "#eaeaea",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Anguished_Shout (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56806,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#979797",
        secondary: "#191919",
        tertiary: "#e6e6e6",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Anguished_Shout (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76902,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#a0a09f",
        secondary: "#1e1e1d",
        tertiary: "#e6e6e6",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Anguished_Shout (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7328736,
        file_size_megabytes: 6.99,
        width: 3072,
        height: 5472,
        primary: "#191919",
        secondary: "#dadada",
        tertiary: "#787877",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Anguished_Shout (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6264131,
        file_size_megabytes: 5.97,
        width: 3072,
        height: 5472,
        primary: "#a4a4a4",
        secondary: "#121212",
        tertiary: "#474746",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Anguished_Shout (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5684931,
        file_size_megabytes: 5.42,
        width: 3072,
        height: 5472,
        primary: "#191918",
        secondary: "#9b9b9b",
        tertiary: "#818181",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Anguished_Shout (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8114569,
        file_size_megabytes: 7.74,
        width: 3072,
        height: 5472,
        primary: "#9e9d9c",
        secondary: "#1d1d1c",
        tertiary: "#e6e6e6",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Chase_Scene: {
    environment_title: "Chase_Scene",
    images: [
      {
        original_file_name: "Chase_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76666,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#c9c9c9",
        secondary: "#696968",
        tertiary: "#1d1d1d",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Chase_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 81841,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#2d2d2d",
        secondary: "#dddddd",
        tertiary: "#b0b0b0",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Chase_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 66864,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#7d7d7d",
        secondary: "#e6e6e6",
        tertiary: "#1f1f1f",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Chase_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 75480,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d7d7d7",
        secondary: "#151514",
        tertiary: "#4f4f4e",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Chase_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8078694,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#818181",
        secondary: "#e8e8e7",
        tertiary: "#1c1c1c",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Chase_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10277895,
        file_size_megabytes: 9.8,
        width: 3072,
        height: 5472,
        primary: "#272727",
        secondary: "#e0e0e0",
        tertiary: "#b0b0af",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Chase_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7483723,
        file_size_megabytes: 7.14,
        width: 3072,
        height: 5472,
        primary: "#7d7d7d",
        secondary: "#e6e6e6",
        tertiary: "#1d1d1d",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Chase_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7089923,
        file_size_megabytes: 6.76,
        width: 3072,
        height: 5472,
        primary: "#d7d7d6",
        secondary: "#141414",
        tertiary: "#4f4f4e",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Confession_Scene: {
    environment_title: "Confession_Scene",
    images: [
      {
        original_file_name: "Confession_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31932,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c9beb1",
        secondary: "#69625e",
        tertiary: "#090707",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Confession_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36725,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#7c7c7c",
        secondary: "#bababa",
        tertiary: "#848484",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Confession_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33702,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c3c1c1",
        secondary: "#555452",
        tertiary: "#060606",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Confession_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22141,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#cbcbcb",
        secondary: "#050505",
        tertiary: "#555555",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Confession_Scene (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3482887,
        file_size_megabytes: 3.32,
        width: 3072,
        height: 5472,
        primary: "#ccc1b5",
        secondary: "#69615c",
        tertiary: "#090707",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Confession_Scene (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3117042,
        file_size_megabytes: 2.97,
        width: 3072,
        height: 5472,
        primary: "#7c7c7c",
        secondary: "#848484",
        tertiary: "#b9b9b9",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Confession_Scene (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3431981,
        file_size_megabytes: 3.27,
        width: 3072,
        height: 5472,
        primary: "#c3c1c0",
        secondary: "#060606",
        tertiary: "#555351",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Confession_Scene (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2140415,
        file_size_megabytes: 2.04,
        width: 3072,
        height: 5472,
        primary: "#c9c9c9",
        secondary: "#050505",
        tertiary: "#565656",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Dynamic_Kick: {
    environment_title: "Dynamic_Kick",
    images: [
      {
        original_file_name: "Dynamic_Kick (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52561,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#161615",
        secondary: "#c0c0c0",
        tertiary: "#757573",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Kick (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50831,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#282828",
        secondary: "#989897",
        tertiary: "#d7d7d6",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Kick (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42787,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dedede",
        secondary: "#4b4c49",
        tertiary: "#1c1c1a",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Kick (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56037,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#757575",
        secondary: "#eeeade",
        tertiary: "#1a1a1a",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Kick (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4757516,
        file_size_megabytes: 4.54,
        width: 3072,
        height: 5472,
        primary: "#161615",
        secondary: "#c0c0c0",
        tertiary: "#757573",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Kick (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5435370,
        file_size_megabytes: 5.18,
        width: 3072,
        height: 5472,
        primary: "#282827",
        secondary: "#9b9a9a",
        tertiary: "#d7d7d6",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Kick (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3927738,
        file_size_megabytes: 3.75,
        width: 3072,
        height: 5472,
        primary: "#dedede",
        secondary: "#1b1b1a",
        tertiary: "#484845",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Kick (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5541834,
        file_size_megabytes: 5.29,
        width: 3072,
        height: 5472,
        primary: "#747576",
        secondary: "#eeeadf",
        tertiary: "#191919",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Energy_Blast: {
    environment_title: "Energy_Blast",
    images: [
      {
        original_file_name: "Energy_Blast (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52275,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c5c5c5",
        secondary: "#616161",
        tertiary: "#070707",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Energy_Blast (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34373,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c8c8c8",
        secondary: "#4e4e4e",
        tertiary: "#070707",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Energy_Blast (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58353,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d6d6d6",
        secondary: "#6f6f6f",
        tertiary: "#0d0d0d",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Energy_Blast (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 69037,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#bcbdbc",
        secondary: "#6b6b6a",
        tertiary: "#949492",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Energy_Blast (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4651610,
        file_size_megabytes: 4.44,
        width: 3072,
        height: 5472,
        primary: "#c5c5c5",
        secondary: "#616161",
        tertiary: "#070707",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Energy_Blast (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3098623,
        file_size_megabytes: 2.96,
        width: 3072,
        height: 5472,
        primary: "#c9c9c9",
        secondary: "#4e4e4d",
        tertiary: "#060606",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Energy_Blast (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5567130,
        file_size_megabytes: 5.31,
        width: 3072,
        height: 5472,
        primary: "#d5d5d5",
        secondary: "#6f6f6f",
        tertiary: "#0d0d0d",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Energy_Blast (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6321964,
        file_size_megabytes: 6.03,
        width: 3072,
        height: 5472,
        primary: "#bcbcbb",
        secondary: "#949492",
        tertiary: "#6b6b6a",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Hero_Landing: {
    environment_title: "Hero_Landing",
    images: [
      {
        original_file_name: "Hero_Landing (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27287,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c6c6c7",
        secondary: "#1d1d1d",
        tertiary: "#f3f3f3",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hero_Landing (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59501,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#2c2b2a",
        secondary: "#dfdfde",
        tertiary: "#b8b8b7",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hero_Landing (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47601,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#191817",
        secondary: "#9b9796",
        tertiary: "#ebe2da",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hero_Landing (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50014,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dde3e5",
        secondary: "#5ca1b6",
        tertiary: "#151616",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hero_Landing (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2404530,
        file_size_megabytes: 2.29,
        width: 3072,
        height: 5472,
        primary: "#c6c6c7",
        secondary: "#1c1c1c",
        tertiary: "#f3f3f3",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hero_Landing (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5450401,
        file_size_megabytes: 5.2,
        width: 3072,
        height: 5472,
        primary: "#2b2a29",
        secondary: "#dedede",
        tertiary: "#b8b8b7",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hero_Landing (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4987219,
        file_size_megabytes: 4.76,
        width: 3072,
        height: 5472,
        primary: "#181615",
        secondary: "#9b9796",
        tertiary: "#ece2da",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hero_Landing (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3797341,
        file_size_megabytes: 3.62,
        width: 3072,
        height: 5472,
        primary: "#dde3e6",
        secondary: "#151515",
        tertiary: "#5ba0b5",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Hopeful_Smile: {
    environment_title: "Hopeful_Smile",
    images: [
      {
        original_file_name: "Hopeful_Smile (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56490,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#969696",
        secondary: "#0b0b0b",
        tertiary: "#e5e5e5",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hopeful_Smile (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43811,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d5d3cc",
        secondary: "#666664",
        tertiary: "#90908d",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hopeful_Smile (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34694,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c6c6c5",
        secondary: "#171717",
        tertiary: "#6c6d6b",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hopeful_Smile (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36516,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c3c3c2",
        secondary: "#525251",
        tertiary: "#050505",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Hopeful_Smile (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5821585,
        file_size_megabytes: 5.55,
        width: 3072,
        height: 5472,
        primary: "#969696",
        secondary: "#0b0b0b",
        tertiary: "#e5e5e5",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hopeful_Smile (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4475987,
        file_size_megabytes: 4.27,
        width: 3072,
        height: 5472,
        primary: "#d1cfc8",
        secondary: "#5f5f5e",
        tertiary: "#878784",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hopeful_Smile (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3474818,
        file_size_megabytes: 3.31,
        width: 3072,
        height: 5472,
        primary: "#c6c5c4",
        secondary: "#161616",
        tertiary: "#6c6d6b",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Hopeful_Smile (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2831474,
        file_size_megabytes: 2.7,
        width: 3072,
        height: 5472,
        primary: "#c3c3c2",
        secondary: "#525250",
        tertiary: "#050505",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Power_Up: {
    environment_title: "Power_Up",
    images: [
      {
        original_file_name: "Power_Up (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62565,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#1f1f1f",
        secondary: "#e2e2e2",
        tertiary: "#b7b7b7",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Power_Up (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48736,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#cccccc",
        secondary: "#1b1b1b",
        tertiary: "#838282",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Power_Up (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55696,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d8d7d7",
        secondary: "#1d1d1d",
        tertiary: "#a09f9f",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Power_Up (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70014,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d1d1d1",
        secondary: "#131313",
        tertiary: "#474747",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Power_Up (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6273232,
        file_size_megabytes: 5.98,
        width: 3072,
        height: 5472,
        primary: "#1b1b1b",
        secondary: "#e2e2e1",
        tertiary: "#b8b7b7",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Power_Up (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5683366,
        file_size_megabytes: 5.42,
        width: 3072,
        height: 5472,
        primary: "#d0d0d0",
        secondary: "#1b1b1b",
        tertiary: "#838381",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Power_Up (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5739432,
        file_size_megabytes: 5.47,
        width: 3072,
        height: 5472,
        primary: "#d4d4d3",
        secondary: "#1d1d1d",
        tertiary: "#7e7e7e",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Power_Up (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7057129,
        file_size_megabytes: 6.73,
        width: 3072,
        height: 5472,
        primary: "#d1d1d1",
        secondary: "#121212",
        tertiary: "#474747",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Reunion_Hug: {
    environment_title: "Reunion_Hug",
    images: [
      {
        original_file_name: "Reunion_Hug (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40906,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#181818",
        secondary: "#d8d8d8",
        tertiary: "#6a6a6a",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Reunion_Hug (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 67444,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#dbdbdb",
        secondary: "#1a1a1a",
        tertiary: "#5f5f5f",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Reunion_Hug (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34834,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e3d5c3",
        secondary: "#796b62",
        tertiary: "#0f0d0c",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Reunion_Hug (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53278,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#a9a9a9",
        secondary: "#b4b4b4",
        tertiary: "#242424",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Reunion_Hug (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4543069,
        file_size_megabytes: 4.33,
        width: 3072,
        height: 5472,
        primary: "#181817",
        secondary: "#d8d8d7",
        tertiary: "#6c6c6b",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Reunion_Hug (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6221728,
        file_size_megabytes: 5.93,
        width: 3072,
        height: 5472,
        primary: "#dbdbdb",
        secondary: "#1a1a1a",
        tertiary: "#60605f",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Reunion_Hug (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3530906,
        file_size_megabytes: 3.37,
        width: 3072,
        height: 5472,
        primary: "#e3d4c2",
        secondary: "#78695e",
        tertiary: "#0e0d0c",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Reunion_Hug (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5604524,
        file_size_megabytes: 5.34,
        width: 3072,
        height: 5472,
        primary: "#a9a9aa",
        secondary: "#b4b4b4",
        tertiary: "#1d1d1d",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Silent_Pain: {
    environment_title: "Silent_Pain",
    images: [
      {
        original_file_name: "Silent_Pain (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45886,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bfbfbf",
        secondary: "#6e6e6e",
        tertiary: "#939493",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Silent_Pain (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58084,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c6c6c6",
        secondary: "#656464",
        tertiary: "#0a0a0a",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Silent_Pain (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33105,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d2d2d2",
        secondary: "#717171",
        tertiary: "#0b0b0b",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Silent_Pain (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51622,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#bcbcbc",
        secondary: "#555555",
        tertiary: "#070707",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Silent_Pain (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5072295,
        file_size_megabytes: 4.84,
        width: 3072,
        height: 5472,
        primary: "#b7b7b7",
        secondary: "#6e6e6d",
        tertiary: "#939493",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Silent_Pain (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6073207,
        file_size_megabytes: 5.79,
        width: 3072,
        height: 5472,
        primary: "#c1c1c1",
        secondary: "#676767",
        tertiary: "#0a0a0a",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Silent_Pain (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3331425,
        file_size_megabytes: 3.18,
        width: 3072,
        height: 5472,
        primary: "#6f6f6f",
        secondary: "#d2d2d2",
        tertiary: "#090909",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Silent_Pain (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5187176,
        file_size_megabytes: 4.95,
        width: 3072,
        height: 5472,
        primary: "#bbbbbb",
        secondary: "#595958",
        tertiary: "#070707",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Sudden_Dodge: {
    environment_title: "Sudden_Dodge",
    images: [
      {
        original_file_name: "Sudden_Dodge (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 60311,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d1d1d0",
        secondary: "#191919",
        tertiary: "#545452",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Dodge (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63585,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#aaaaaa",
        secondary: "#111111",
        tertiary: "#646463",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Dodge (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58814,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#dcdcdb",
        secondary: "#161615",
        tertiary: "#6e6d6c",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Dodge (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64891,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#1f1f1e",
        secondary: "#dededd",
        tertiary: "#797978",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Dodge (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5197205,
        file_size_megabytes: 4.96,
        width: 3072,
        height: 5472,
        primary: "#d0d0cf",
        secondary: "#191918",
        tertiary: "#50504e",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Dodge (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5733420,
        file_size_megabytes: 5.47,
        width: 3072,
        height: 5472,
        primary: "#aaaaaa",
        secondary: "#101010",
        tertiary: "#646363",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Dodge (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5580133,
        file_size_megabytes: 5.32,
        width: 3072,
        height: 5472,
        primary: "#dcdcdb",
        secondary: "#181817",
        tertiary: "#6e6d6b",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Dodge (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5830148,
        file_size_megabytes: 5.56,
        width: 3072,
        height: 5472,
        primary: "#1d1d1d",
        secondary: "#dddddc",
        tertiary: "#7a7a78",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Sudden_Realization: {
    environment_title: "Sudden_Realization",
    images: [
      {
        original_file_name: "Sudden_Realization (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39212,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#ababa8",
        secondary: "#050505",
        tertiary: "#62625f",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Realization (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48331,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#8f8f8f",
        secondary: "#0a0a0a",
        tertiary: "#e8e8e8",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Realization (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46329,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cfcfcf",
        secondary: "#6e6e6e",
        tertiary: "#090909",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Realization (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49627,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#8f8e8d",
        secondary: "#e8e8e8",
        tertiary: "#111111",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sudden_Realization (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3815960,
        file_size_megabytes: 3.64,
        width: 3072,
        height: 5472,
        primary: "#ababa8",
        secondary: "#63625f",
        tertiary: "#040404",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Realization (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4980082,
        file_size_megabytes: 4.75,
        width: 3072,
        height: 5472,
        primary: "#8e8e8e",
        secondary: "#0a0a0a",
        tertiary: "#e8e8e8",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Realization (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4510960,
        file_size_megabytes: 4.3,
        width: 3072,
        height: 5472,
        primary: "#cacaca",
        secondary: "#676766",
        tertiary: "#080808",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sudden_Realization (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5520085,
        file_size_megabytes: 5.26,
        width: 3072,
        height: 5472,
        primary: "#8f8e8d",
        secondary: "#111110",
        tertiary: "#e8e8e8",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Sword_Clash: {
    environment_title: "Sword_Clash",
    images: [
      {
        original_file_name: "Sword_Clash (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39251,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#282828",
        secondary: "#d9d9d9",
        tertiary: "#a8a8a8",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sword_Clash (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41512,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#303030",
        secondary: "#afafaf",
        tertiary: "#e1e1e1",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sword_Clash (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56764,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#272727",
        secondary: "#e0e0e0",
        tertiary: "#b3b3b3",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sword_Clash (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 74502,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#dbdbdb",
        secondary: "#202020",
        tertiary: "#7c7c7c",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Sword_Clash (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3981061,
        file_size_megabytes: 3.8,
        width: 3072,
        height: 5472,
        primary: "#252525",
        secondary: "#d5d5d5",
        tertiary: "#a8a8a7",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sword_Clash (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3999769,
        file_size_megabytes: 3.81,
        width: 3072,
        height: 5472,
        primary: "#2b2b2b",
        secondary: "#afafaf",
        tertiary: "#e1e1e1",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sword_Clash (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5535411,
        file_size_megabytes: 5.28,
        width: 3072,
        height: 5472,
        primary: "#222222",
        secondary: "#dddddd",
        tertiary: "#b4b4b3",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Sword_Clash (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7750343,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#dbdbdb",
        secondary: "#1f1f1f",
        tertiary: "#7c7c7c",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  },
  Tearful_Goodbye: {
    environment_title: "Tearful_Goodbye",
    images: [
      {
        original_file_name: "Tearful_Goodbye (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40393,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bebebe",
        secondary: "#0f0f0f",
        tertiary: "#727272",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Tearful_Goodbye (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31174,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#acacac",
        secondary: "#575755",
        tertiary: "#050505",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Tearful_Goodbye (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44008,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#2d2d2d",
        secondary: "#dbdbda",
        tertiary: "#909090",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Tearful_Goodbye (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42230,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a7a7a7",
        secondary: "#1b1b1b",
        tertiary: "#cdcdcd",
        branch: "Anime",
        folder: "Manga",
        type: "min"
      },
      {
        original_file_name: "Tearful_Goodbye (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4188406,
        file_size_megabytes: 3.99,
        width: 3072,
        height: 5472,
        primary: "#bebebe",
        secondary: "#0e0e0e",
        tertiary: "#727272",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Tearful_Goodbye (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2846851,
        file_size_megabytes: 2.71,
        width: 3072,
        height: 5472,
        primary: "#ababab",
        secondary: "#595958",
        tertiary: "#050505",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Tearful_Goodbye (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4678415,
        file_size_megabytes: 4.46,
        width: 3072,
        height: 5472,
        primary: "#2d2d2d",
        secondary: "#dadada",
        tertiary: "#909090",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      },
      {
        original_file_name: "Tearful_Goodbye (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3797879,
        file_size_megabytes: 3.62,
        width: 3072,
        height: 5472,
        primary: "#a7a7a7",
        secondary: "#1b1b1b",
        tertiary: "#cdcdcd",
        branch: "Anime",
        folder: "Manga",
        type: "max"
      }
    ]
  }
};
export default Anime_Manga;
