import { EnvironmentEntry } from "@/types/database";
const Graphic_Vector: Record<string, EnvironmentEntry> = {
  Celestial_Precision: {
    environment_title: "Celestial_Precision",
    images: [
      {
        original_file_name: "Celestial_Precision (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38727,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#efb67f",
        secondary: "#12111c",
        tertiary: "#67b6b9",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Celestial_Precision (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39855,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e7b376",
        secondary: "#121a29",
        tertiary: "#59b6bd",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Celestial_Precision (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37179,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e9ac72",
        secondary: "#61b1c1",
        tertiary: "#131723",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Celestial_Precision (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41495,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e4ad7c",
        secondary: "#111528",
        tertiary: "#61b1be",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Celestial_Precision (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5981216,
        file_size_megabytes: 5.7,
        width: 3072,
        height: 5472,
        primary: "#f0b67f",
        secondary: "#12121c",
        tertiary: "#67b8ba",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Celestial_Precision (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6190793,
        file_size_megabytes: 5.9,
        width: 3072,
        height: 5472,
        primary: "#e8b375",
        secondary: "#121a29",
        tertiary: "#57b6bd",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Celestial_Precision (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5638474,
        file_size_megabytes: 5.38,
        width: 3072,
        height: 5472,
        primary: "#eaab71",
        secondary: "#61b1c1",
        tertiary: "#121723",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Celestial_Precision (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6232471,
        file_size_megabytes: 5.94,
        width: 3072,
        height: 5472,
        primary: "#e5ad7b",
        secondary: "#111629",
        tertiary: "#62b1bf",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Digital_Flora: {
    environment_title: "Digital_Flora",
    images: [
      {
        original_file_name: "Digital_Flora (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41247,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#0c2931",
        secondary: "#aee26a",
        tertiary: "#56b371",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Digital_Flora (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46077,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#51c18d",
        secondary: "#08222b",
        tertiary: "#b3df57",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Digital_Flora (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49441,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#70cc7c",
        secondary: "#0a2b2f",
        tertiary: "#398660",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Digital_Flora (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41134,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#52b86c",
        secondary: "#b2e778",
        tertiary: "#061b22",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Digital_Flora (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7253920,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#0c2a32",
        secondary: "#afe36a",
        tertiary: "#55b370",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Digital_Flora (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7397705,
        file_size_megabytes: 7.06,
        width: 3072,
        height: 5472,
        primary: "#4fc18d",
        secondary: "#08222b",
        tertiary: "#b3e053",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Digital_Flora (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7982514,
        file_size_megabytes: 7.61,
        width: 3072,
        height: 5472,
        primary: "#6fcc7c",
        secondary: "#0a2b30",
        tertiary: "#398760",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Digital_Flora (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7160705,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#50b86c",
        secondary: "#b2e876",
        tertiary: "#061b22",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Dynamic_Waves: {
    environment_title: "Dynamic_Waves",
    images: [
      {
        original_file_name: "Dynamic_Waves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55319,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ebe7d8",
        secondary: "#1c4a63",
        tertiary: "#ee734a",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Waves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39132,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d7493b",
        secondary: "#223046",
        tertiary: "#f8b354",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Waves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50339,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ddf0f3",
        secondary: "#0e3456",
        tertiary: "#75bcc9",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Waves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41848,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e1ba98",
        secondary: "#58b2c0",
        tertiary: "#101d2f",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Dynamic_Waves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8156360,
        file_size_megabytes: 7.78,
        width: 3072,
        height: 5472,
        primary: "#ede8d8",
        secondary: "#1c4b63",
        tertiary: "#f0734a",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Waves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8213297,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#d8493b",
        secondary: "#223046",
        tertiary: "#f9b354",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Waves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6801826,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#d9eef2",
        secondary: "#0d3456",
        tertiary: "#70b9c7",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Dynamic_Waves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7460307,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#e3bb97",
        secondary: "#58b2c1",
        tertiary: "#101d2f",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Geometric_Harmony: {
    environment_title: "Geometric_Harmony",
    images: [
      {
        original_file_name: "Geometric_Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37743,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#34a0aa",
        secondary: "#212e40",
        tertiary: "#f47640",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40298,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1c3040",
        secondary: "#f3783f",
        tertiary: "#78bdac",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37838,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#f07648",
        secondary: "#143952",
        tertiary: "#e4eed9",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39838,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#f06c41",
        secondary: "#1d3d50",
        tertiary: "#e4e8ca",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6092306,
        file_size_megabytes: 5.81,
        width: 3072,
        height: 5472,
        primary: "#35a0aa",
        secondary: "#202f40",
        tertiary: "#f57740",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6263890,
        file_size_megabytes: 5.97,
        width: 3072,
        height: 5472,
        primary: "#1c3040",
        secondary: "#f4783e",
        tertiary: "#76bead",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6402262,
        file_size_megabytes: 6.11,
        width: 3072,
        height: 5472,
        primary: "#f17647",
        secondary: "#143a53",
        tertiary: "#e7efd9",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6570159,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#f16c40",
        secondary: "#1d3d51",
        tertiary: "#e3e8c9",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Layered_Landscapes: {
    environment_title: "Layered_Landscapes",
    images: [
      {
        original_file_name: "Layered_Landscapes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33117,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#274e4e",
        secondary: "#e3b662",
        tertiary: "#c7e5d1",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Layered_Landscapes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29827,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#28656b",
        secondary: "#d2c081",
        tertiary: "#5b9e8e",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Layered_Landscapes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29603,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#3d5f62",
        secondary: "#eba26b",
        tertiary: "#80a08c",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Layered_Landscapes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29589,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#59958e",
        secondary: "#edcea0",
        tertiary: "#22363f",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Layered_Landscapes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6395896,
        file_size_megabytes: 6.1,
        width: 3072,
        height: 5472,
        primary: "#274f4f",
        secondary: "#c6e5d1",
        tertiary: "#e3b662",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Layered_Landscapes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6730120,
        file_size_megabytes: 6.42,
        width: 3072,
        height: 5472,
        primary: "#28656b",
        secondary: "#d6c081",
        tertiary: "#5b9e8e",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Layered_Landscapes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6066578,
        file_size_megabytes: 5.79,
        width: 3072,
        height: 5472,
        primary: "#3d6063",
        secondary: "#eba26b",
        tertiary: "#80a08c",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Layered_Landscapes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6575183,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#5e9a93",
        secondary: "#edcd9f",
        tertiary: "#233640",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Minimalist_Portrait: {
    environment_title: "Minimalist_Portrait",
    images: [
      {
        original_file_name: "Minimalist_Portrait (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25123,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#1a1b2b",
        secondary: "#ccb6c0",
        tertiary: "#f59579",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portrait (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28706,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#2d242e",
        secondary: "#e3997a",
        tertiary: "#803f37",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portrait (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 24987,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#373d55",
        secondary: "#995c5f",
        tertiary: "#f7f5ed",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portrait (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16319,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#8c2454",
        secondary: "#cf87c0",
        tertiary: "#efdec8",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portrait (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5288546,
        file_size_megabytes: 5.04,
        width: 3072,
        height: 5472,
        primary: "#1a1c2b",
        secondary: "#ccb6c0",
        tertiary: "#f69579",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portrait (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5247260,
        file_size_megabytes: 5.0,
        width: 3072,
        height: 5472,
        primary: "#2d252e",
        secondary: "#e39879",
        tertiary: "#803f38",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portrait (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4677769,
        file_size_megabytes: 4.46,
        width: 3072,
        height: 5472,
        primary: "#363d55",
        secondary: "#995c5f",
        tertiary: "#f7f6ed",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portrait (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6703732,
        file_size_megabytes: 6.39,
        width: 3072,
        height: 5472,
        primary: "#cf87c0",
        secondary: "#882454",
        tertiary: "#efdec8",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Playful_Typography: {
    environment_title: "Playful_Typography",
    images: [
      {
        original_file_name: "Playful_Typography (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45057,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#ec9f49",
        secondary: "#1b232e",
        tertiary: "#5abaca",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Playful_Typography (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56539,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#efa04d",
        secondary: "#1b272e",
        tertiary: "#4cb8b9",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Playful_Typography (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58863,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ea7d51",
        secondary: "#3fbcc2",
        tertiary: "#1d212b",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Playful_Typography (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40812,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#ec964c",
        secondary: "#44b1b6",
        tertiary: "#1a1c25",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Playful_Typography (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6607608,
        file_size_megabytes: 6.3,
        width: 3072,
        height: 5472,
        primary: "#ee9f48",
        secondary: "#1b242e",
        tertiary: "#59bacb",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Playful_Typography (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7481551,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#f0a04b",
        secondary: "#1b272f",
        tertiary: "#4bb8b9",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Playful_Typography (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7764182,
        file_size_megabytes: 7.4,
        width: 3072,
        height: 5472,
        primary: "#eb7652",
        secondary: "#3ebdc2",
        tertiary: "#1c222c",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Playful_Typography (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5869608,
        file_size_megabytes: 5.6,
        width: 3072,
        height: 5472,
        primary: "#ee974b",
        secondary: "#43b2b6",
        tertiary: "#1a1c26",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Symmetrical_Mandala: {
    environment_title: "Symmetrical_Mandala",
    images: [
      {
        original_file_name: "Symmetrical_Mandala (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 70726,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d29f77",
        secondary: "#212c33",
        tertiary: "#806a59",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Symmetrical_Mandala (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64150,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ce8a5b",
        secondary: "#223038",
        tertiary: "#7f5e49",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Symmetrical_Mandala (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68646,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d4925f",
        secondary: "#20323c",
        tertiary: "#8c6555",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Symmetrical_Mandala (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76124,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#ca9e7d",
        secondary: "#886653",
        tertiary: "#171821",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Symmetrical_Mandala (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9260133,
        file_size_megabytes: 8.83,
        width: 3072,
        height: 5472,
        primary: "#d39e74",
        secondary: "#202c34",
        tertiary: "#816a5a",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Symmetrical_Mandala (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9981789,
        file_size_megabytes: 9.52,
        width: 3072,
        height: 5472,
        primary: "#cf8a59",
        secondary: "#213039",
        tertiary: "#7f5d49",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Symmetrical_Mandala (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9946549,
        file_size_megabytes: 9.49,
        width: 3072,
        height: 5472,
        primary: "#d5915d",
        secondary: "#20323d",
        tertiary: "#8c6555",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Symmetrical_Mandala (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9887803,
        file_size_megabytes: 9.43,
        width: 3072,
        height: 5472,
        primary: "#cb9d7b",
        secondary: "#896653",
        tertiary: "#171922",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Tropical_Patterns: {
    environment_title: "Tropical_Patterns",
    images: [
      {
        original_file_name: "Tropical_Patterns (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63098,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e2bd7d",
        secondary: "#265a53",
        tertiary: "#85bc9d",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Tropical_Patterns (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 60323,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#efb071",
        secondary: "#2c5747",
        tertiary: "#799267",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Tropical_Patterns (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63056,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ecb678",
        secondary: "#295046",
        tertiary: "#5f9073",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Tropical_Patterns (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 63114,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ecc288",
        secondary: "#2d5d5c",
        tertiary: "#0f1b21",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Tropical_Patterns (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8850473,
        file_size_megabytes: 8.44,
        width: 3072,
        height: 5472,
        primary: "#e4bd7c",
        secondary: "#255a53",
        tertiary: "#85bc9d",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Tropical_Patterns (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8766078,
        file_size_megabytes: 8.36,
        width: 3072,
        height: 5472,
        primary: "#f0b071",
        secondary: "#2b5748",
        tertiary: "#799266",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Tropical_Patterns (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8895093,
        file_size_megabytes: 8.48,
        width: 3072,
        height: 5472,
        primary: "#eeb677",
        secondary: "#295146",
        tertiary: "#5e8f73",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Tropical_Patterns (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8657323,
        file_size_megabytes: 8.26,
        width: 3072,
        height: 5472,
        primary: "#eec287",
        secondary: "#2d5d5d",
        tertiary: "#0f1b21",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  },
  Urban_Blueprint: {
    environment_title: "Urban_Blueprint",
    images: [
      {
        original_file_name: "Urban_Blueprint (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 76828,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d2d7dd",
        secondary: "#20435f",
        tertiary: "#7a8895",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Urban_Blueprint (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 85954,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#acbaca",
        secondary: "#1f3d58",
        tertiary: "#647789",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Urban_Blueprint (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 82744,
        file_size_megabytes: 0.08,
        width: 360,
        height: 640,
        primary: "#abbed4",
        secondary: "#1d4364",
        tertiary: "#657c93",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Urban_Blueprint (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 74167,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#1b4764",
        secondary: "#8ea6bb",
        tertiary: "#e2eff6",
        branch: "Graphic",
        folder: "Vector",
        type: "min"
      },
      {
        original_file_name: "Urban_Blueprint (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 13037750,
        file_size_megabytes: 12.43,
        width: 3072,
        height: 5472,
        primary: "#d2d7de",
        secondary: "#204460",
        tertiary: "#7a8996",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Urban_Blueprint (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 14257403,
        file_size_megabytes: 13.6,
        width: 3072,
        height: 5472,
        primary: "#abbacb",
        secondary: "#1f3d59",
        tertiary: "#65788b",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Urban_Blueprint (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 13544242,
        file_size_megabytes: 12.92,
        width: 3072,
        height: 5472,
        primary: "#aabed4",
        secondary: "#1d4465",
        tertiary: "#657c93",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      },
      {
        original_file_name: "Urban_Blueprint (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 13476782,
        file_size_megabytes: 12.85,
        width: 3072,
        height: 5472,
        primary: "#1b4765",
        secondary: "#8ea6bc",
        tertiary: "#e2f0f7",
        branch: "Graphic",
        folder: "Vector",
        type: "max"
      }
    ]
  }
};
export default Graphic_Vector;
