import { EnvironmentEntry } from "@/types/database";
const Graphic_ArtDeco: Record<string, EnvironmentEntry> = {
  Chrysler_Elegance: {
    environment_title: "Chrysler_Elegance",
    images: [
      {
        original_file_name: "Chrysler_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56915,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#251911",
        secondary: "#e0c9a2",
        tertiary: "#694a2f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Chrysler_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51189,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#211d17",
        secondary: "#e2c698",
        tertiary: "#f9f6d9",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Chrysler_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49082,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#cbae78",
        secondary: "#121c1c",
        tertiary: "#7c6f4f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Chrysler_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52360,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#847052",
        secondary: "#e9c281",
        tertiary: "#f8e8b7",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Chrysler_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7726146,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#251811",
        secondary: "#e1caa2",
        tertiary: "#694a2f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Chrysler_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7167427,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#211c16",
        secondary: "#e5c799",
        tertiary: "#f9f6d9",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Chrysler_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8029140,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#cbae77",
        secondary: "#111c1c",
        tertiary: "#7c704f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Chrysler_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8913886,
        file_size_megabytes: 8.5,
        width: 3072,
        height: 5472,
        primary: "#847051",
        secondary: "#e9c382",
        tertiary: "#f8e9b7",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Deco_Sunburst: {
    environment_title: "Deco_Sunburst",
    images: [
      {
        original_file_name: "Deco_Sunburst (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59476,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#1c1512",
        secondary: "#b6884b",
        tertiary: "#f8f2c9",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Deco_Sunburst (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61010,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#120d0b",
        secondary: "#cb9c51",
        tertiary: "#f7f3cb",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Deco_Sunburst (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 69148,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#caa062",
        secondary: "#160e0a",
        tertiary: "#f5dc9d",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Deco_Sunburst (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 73943,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#c6a164",
        secondary: "#18100f",
        tertiary: "#593a1b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Deco_Sunburst (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7906987,
        file_size_megabytes: 7.54,
        width: 3072,
        height: 5472,
        primary: "#1c1412",
        secondary: "#c9964f",
        tertiary: "#f8f3c9",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Deco_Sunburst (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7047835,
        file_size_megabytes: 6.72,
        width: 3072,
        height: 5472,
        primary: "#110d0a",
        secondary: "#cb9c51",
        tertiary: "#f8f4ca",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Deco_Sunburst (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8263569,
        file_size_megabytes: 7.88,
        width: 3072,
        height: 5472,
        primary: "#cba060",
        secondary: "#150e09",
        tertiary: "#f7ecba",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Deco_Sunburst (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9232009,
        file_size_megabytes: 8.8,
        width: 3072,
        height: 5472,
        primary: "#c8a164",
        secondary: "#18100e",
        tertiary: "#5a3a1a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Elegant_Monogram: {
    environment_title: "Elegant_Monogram",
    images: [
      {
        original_file_name: "Elegant_Monogram (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53022,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c9b190",
        secondary: "#1d1614",
        tertiary: "#796753",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Elegant_Monogram (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48705,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#bba98f",
        secondary: "#0d0a0a",
        tertiary: "#6f5f4f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Elegant_Monogram (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40782,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#31251c",
        secondary: "#f8dfc5",
        tertiary: "#af9677",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Elegant_Monogram (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57753,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c19e78",
        secondary: "#150e09",
        tertiary: "#533c25",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Elegant_Monogram (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7659179,
        file_size_megabytes: 7.3,
        width: 3072,
        height: 5472,
        primary: "#c7ae8c",
        secondary: "#1d1615",
        tertiary: "#78654f",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Elegant_Monogram (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6053039,
        file_size_megabytes: 5.77,
        width: 3072,
        height: 5472,
        primary: "#b7a387",
        secondary: "#665644",
        tertiary: "#0c0909",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Elegant_Monogram (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6369321,
        file_size_megabytes: 6.07,
        width: 3072,
        height: 5472,
        primary: "#2e2117",
        secondary: "#f9dfc5",
        tertiary: "#b09676",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Elegant_Monogram (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7242416,
        file_size_megabytes: 6.91,
        width: 3072,
        height: 5472,
        primary: "#c19e76",
        secondary: "#140d09",
        tertiary: "#543c23",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Gilded_Roaring_Twenties: {
    environment_title: "Gilded_Roaring_Twenties",
    images: [
      {
        original_file_name: "Gilded_Roaring_Twenties (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64040,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#dfc085",
        secondary: "#8f7650",
        tertiary: "#ad9a74",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 57575,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#111513",
        secondary: "#ad864c",
        tertiary: "#f8e7bc",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58823,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ba9159",
        secondary: "#100c09",
        tertiary: "#f7ecc7",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59730,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e3c68f",
        secondary: "#b39665",
        tertiary: "#956f3c",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8216900,
        file_size_megabytes: 7.84,
        width: 3072,
        height: 5472,
        primary: "#e0c084",
        secondary: "#90754d",
        tertiary: "#ad9a72",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7607742,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#101513",
        secondary: "#ae864b",
        tertiary: "#f9e8bb",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7517565,
        file_size_megabytes: 7.17,
        width: 3072,
        height: 5472,
        primary: "#bb9159",
        secondary: "#100b08",
        tertiary: "#f8eec7",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Gilded_Roaring_Twenties (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7105049,
        file_size_megabytes: 6.78,
        width: 3072,
        height: 5472,
        primary: "#e3c58d",
        secondary: "#b39562",
        tertiary: "#956f3b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Golden_Geometries: {
    environment_title: "Golden_Geometries",
    images: [
      {
        original_file_name: "Golden_Geometries (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 73370,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#cbac7d",
        secondary: "#191312",
        tertiary: "#836a4e",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Geometries (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 67857,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c8ae7f",
        secondary: "#141b1e",
        tertiary: "#786c53",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Geometries (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 67333,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c8a779",
        secondary: "#191312",
        tertiary: "#7b6348",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Geometries (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 73309,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#cfb27e",
        secondary: "#151317",
        tertiary: "#75624c",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Geometries (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9192287,
        file_size_megabytes: 8.77,
        width: 3072,
        height: 5472,
        primary: "#cbab7a",
        secondary: "#181312",
        tertiary: "#83694b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Geometries (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8502217,
        file_size_megabytes: 8.11,
        width: 3072,
        height: 5472,
        primary: "#c8ad7b",
        secondary: "#141b1e",
        tertiary: "#786b52",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Geometries (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8441771,
        file_size_megabytes: 8.05,
        width: 3072,
        height: 5472,
        primary: "#c7a675",
        secondary: "#191311",
        tertiary: "#7c6346",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Geometries (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8478930,
        file_size_megabytes: 8.09,
        width: 3072,
        height: 5472,
        primary: "#d0b17a",
        secondary: "#151317",
        tertiary: "#76624a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Golden_Skyline: {
    environment_title: "Golden_Skyline",
    images: [
      {
        original_file_name: "Golden_Skyline (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46219,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e4af46",
        secondary: "#8e5c24",
        tertiary: "#170f08",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Skyline (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45883,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e2b75c",
        secondary: "#865e2f",
        tertiary: "#0f0a06",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Skyline (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55361,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e1b45b",
        secondary: "#21150e",
        tertiary: "#916734",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Skyline (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47894,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e6b65a",
        secondary: "#17100b",
        tertiary: "#8e6a3a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Golden_Skyline (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7356819,
        file_size_megabytes: 7.02,
        width: 3072,
        height: 5472,
        primary: "#e5af45",
        secondary: "#8e5b21",
        tertiary: "#170f08",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Skyline (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6616426,
        file_size_megabytes: 6.31,
        width: 3072,
        height: 5472,
        primary: "#e3b65b",
        secondary: "#855d2b",
        tertiary: "#0f0906",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Skyline (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8279907,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#e3b45a",
        secondary: "#21150d",
        tertiary: "#916631",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Golden_Skyline (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7030801,
        file_size_megabytes: 6.71,
        width: 3072,
        height: 5472,
        primary: "#e6b558",
        secondary: "#17100b",
        tertiary: "#8d6837",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Jazz_Night_Poster: {
    environment_title: "Jazz_Night_Poster",
    images: [
      {
        original_file_name: "Jazz_Night_Poster (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54739,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e0b76a",
        secondary: "#937448",
        tertiary: "#13101c",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Jazz_Night_Poster (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56523,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d0b480",
        secondary: "#100b13",
        tertiary: "#625240",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Jazz_Night_Poster (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 59760,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#dabd8a",
        secondary: "#766046",
        tertiary: "#0d0907",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Jazz_Night_Poster (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55534,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#130e0c",
        secondary: "#dfa954",
        tertiary: "#776549",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Jazz_Night_Poster (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7745115,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#e0b769",
        secondary: "#947546",
        tertiary: "#130f1c",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Jazz_Night_Poster (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7727321,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#d1b47d",
        secondary: "#100b14",
        tertiary: "#5f4d36",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Jazz_Night_Poster (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6359174,
        file_size_megabytes: 6.06,
        width: 3072,
        height: 5472,
        primary: "#dbbe88",
        secondary: "#766041",
        tertiary: "#0d0907",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Jazz_Night_Poster (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6975876,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#130e0b",
        secondary: "#e0a953",
        tertiary: "#5e4527",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Luxury_Invitation: {
    environment_title: "Luxury_Invitation",
    images: [
      {
        original_file_name: "Luxury_Invitation (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62860,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#cfb482",
        secondary: "#7e6c51",
        tertiary: "#140f0b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Luxury_Invitation (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62421,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#c9ab78",
        secondary: "#74644d",
        tertiary: "#120e0b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Luxury_Invitation (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54454,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ceb483",
        secondary: "#110d0e",
        tertiary: "#6e5d43",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Luxury_Invitation (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54042,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c0a678",
        secondary: "#6e5e45",
        tertiary: "#0e0b0a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Luxury_Invitation (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7590150,
        file_size_megabytes: 7.24,
        width: 3072,
        height: 5472,
        primary: "#d0b380",
        secondary: "#7e6b4e",
        tertiary: "#130f0b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Luxury_Invitation (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7248606,
        file_size_megabytes: 6.91,
        width: 3072,
        height: 5472,
        primary: "#c9ab77",
        secondary: "#746349",
        tertiary: "#110e0b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Luxury_Invitation (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7246566,
        file_size_megabytes: 6.91,
        width: 3072,
        height: 5472,
        primary: "#cfb380",
        secondary: "#110d0e",
        tertiary: "#6f5c40",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Luxury_Invitation (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6373039,
        file_size_megabytes: 6.08,
        width: 3072,
        height: 5472,
        primary: "#c0a474",
        secondary: "#6e5c3f",
        tertiary: "#0e0c0a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Opulent_Fan: {
    environment_title: "Opulent_Fan",
    images: [
      {
        original_file_name: "Opulent_Fan (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 64042,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d7ac6d",
        secondary: "#150e09",
        tertiary: "#f6f2d3",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Opulent_Fan (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 67117,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#ca9f5c",
        secondary: "#1b130d",
        tertiary: "#f9e096",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Opulent_Fan (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 68711,
        file_size_megabytes: 0.07,
        width: 360,
        height: 640,
        primary: "#d2a863",
        secondary: "#150e0c",
        tertiary: "#5a4022",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Opulent_Fan (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58342,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#9c7544",
        secondary: "#f8f1d0",
        tertiary: "#160e0a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Opulent_Fan (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8139959,
        file_size_megabytes: 7.76,
        width: 3072,
        height: 5472,
        primary: "#140d08",
        secondary: "#d8ac6c",
        tertiary: "#f8f3d3",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Opulent_Fan (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8831914,
        file_size_megabytes: 8.42,
        width: 3072,
        height: 5472,
        primary: "#cb9f5b",
        secondary: "#1b120c",
        tertiary: "#f9e097",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Opulent_Fan (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9079110,
        file_size_megabytes: 8.66,
        width: 3072,
        height: 5472,
        primary: "#d3a862",
        secondary: "#140e0b",
        tertiary: "#5a401e",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Opulent_Fan (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8275708,
        file_size_megabytes: 7.89,
        width: 3072,
        height: 5472,
        primary: "#9c7543",
        secondary: "#f9f2d0",
        tertiary: "#160d0a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  },
  Theater_Marquee: {
    environment_title: "Theater_Marquee",
    images: [
      {
        original_file_name: "Theater_Marquee (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50208,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#dabe8e",
        secondary: "#69a696",
        tertiary: "#806144",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Theater_Marquee (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41318,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d2ab73",
        secondary: "#1c1611",
        tertiary: "#815a3b",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Theater_Marquee (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44883,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d6ae7b",
        secondary: "#1b1617",
        tertiary: "#82593a",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Theater_Marquee (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40364,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d5a677",
        secondary: "#432b20",
        tertiary: "#52baaf",
        branch: "Graphic",
        folder: "Art Deco",
        type: "min"
      },
      {
        original_file_name: "Theater_Marquee (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7809524,
        file_size_megabytes: 7.45,
        width: 3072,
        height: 5472,
        primary: "#dbbe8d",
        secondary: "#66a797",
        tertiary: "#806142",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Theater_Marquee (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8131753,
        file_size_megabytes: 7.76,
        width: 3072,
        height: 5472,
        primary: "#d2aa71",
        secondary: "#1c1611",
        tertiary: "#805938",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Theater_Marquee (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7936580,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#d7ae7a",
        secondary: "#191415",
        tertiary: "#825939",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      },
      {
        original_file_name: "Theater_Marquee (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8267268,
        file_size_megabytes: 7.88,
        width: 3072,
        height: 5472,
        primary: "#d6a676",
        secondary: "#312019",
        tertiary: "#53baaf",
        branch: "Graphic",
        folder: "Art Deco",
        type: "max"
      }
    ]
  }
};
export default Graphic_ArtDeco;
