import { EnvironmentEntry } from "@/types/database";
const Graphic_2D_Design: Record<string, EnvironmentEntry> = {
  Abstract_Flow: {
    environment_title: "Abstract_Flow",
    images: [
      {
        original_file_name: "Abstract_Flow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48672,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#1e4662",
        secondary: "#e97351",
        tertiary: "#e2e6be",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Abstract_Flow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43819,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e66050",
        secondary: "#1e1c34",
        tertiary: "#f6c14f",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Abstract_Flow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39061,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#223a57",
        secondary: "#f37e52",
        tertiary: "#df335a",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Abstract_Flow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41373,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1f4558",
        secondary: "#f07f46",
        tertiary: "#cfe0ca",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Abstract_Flow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7559791,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#1d4763",
        secondary: "#eb7351",
        tertiary: "#e2e7be",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Abstract_Flow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7548456,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#e75f50",
        secondary: "#1d1c35",
        tertiary: "#f7c14e",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Abstract_Flow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6969950,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#f17e53",
        secondary: "#1e2b49",
        tertiary: "#e1335a",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Abstract_Flow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7163914,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#1e4659",
        secondary: "#f27f46",
        tertiary: "#d0e0ca",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Celestial_Patterns: {
    environment_title: "Celestial_Patterns",
    images: [
      {
        original_file_name: "Celestial_Patterns (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22923,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#16294f",
        secondary: "#bb9aae",
        tertiary: "#596291",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Celestial_Patterns (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39200,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e6af72",
        secondary: "#151829",
        tertiary: "#72b0bd",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Celestial_Patterns (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 30869,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#cad3c4",
        secondary: "#0e233f",
        tertiary: "#689dba",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Celestial_Patterns (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 26605,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#112b54",
        secondary: "#c4e7f0",
        tertiary: "#23699a",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Celestial_Patterns (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6344758,
        file_size_megabytes: 6.05,
        width: 3072,
        height: 5472,
        primary: "#16294f",
        secondary: "#bc9aad",
        tertiary: "#596291",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Celestial_Patterns (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6297580,
        file_size_megabytes: 6.01,
        width: 3072,
        height: 5472,
        primary: "#e6af71",
        secondary: "#151829",
        tertiary: "#71adbb",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Celestial_Patterns (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6242532,
        file_size_megabytes: 5.95,
        width: 3072,
        height: 5472,
        primary: "#cad3c4",
        secondary: "#0e2340",
        tertiary: "#689dba",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Celestial_Patterns (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6555322,
        file_size_megabytes: 6.25,
        width: 3072,
        height: 5472,
        primary: "#122b54",
        secondary: "#c4e7f0",
        tertiary: "#23699a",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  City_Skyline_Silhouette: {
    environment_title: "City_Skyline_Silhouette",
    images: [
      {
        original_file_name: "City_Skyline_Silhouette (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27432,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ef656a",
        secondary: "#322d55",
        tertiary: "#974f76",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "City_Skyline_Silhouette (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27490,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ed5a4e",
        secondary: "#281735",
        tertiary: "#faedc2",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "City_Skyline_Silhouette (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28706,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#312649",
        secondary: "#f8ca79",
        tertiary: "#e85863",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "City_Skyline_Silhouette (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28550,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#db5766",
        secondary: "#252454",
        tertiary: "#7f3b6e",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "City_Skyline_Silhouette (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7131353,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#ef656a",
        secondary: "#322e56",
        tertiary: "#964e74",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "City_Skyline_Silhouette (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6311791,
        file_size_megabytes: 6.02,
        width: 3072,
        height: 5472,
        primary: "#ed5a4d",
        secondary: "#281835",
        tertiary: "#faeec3",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "City_Skyline_Silhouette (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6959853,
        file_size_megabytes: 6.64,
        width: 3072,
        height: 5472,
        primary: "#30264a",
        secondary: "#f8ca78",
        tertiary: "#e85863",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "City_Skyline_Silhouette (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7228289,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#db5766",
        secondary: "#252454",
        tertiary: "#7e3a6f",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Digital_Nomad_Life: {
    environment_title: "Digital_Nomad_Life",
    images: [
      {
        original_file_name: "Digital_Nomad_Life (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41459,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#37514d",
        secondary: "#b66336",
        tertiary: "#f7f7eb",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Digital_Nomad_Life (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43440,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#424739",
        secondary: "#f6cb94",
        tertiary: "#e6ede8",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Digital_Nomad_Life (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37371,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#3c4d4d",
        secondary: "#a25735",
        tertiary: "#f7efdc",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Digital_Nomad_Life (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45373,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#49504a",
        secondary: "#f3c498",
        tertiary: "#ecf4ed",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Digital_Nomad_Life (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5288954,
        file_size_megabytes: 5.04,
        width: 3072,
        height: 5472,
        primary: "#35514d",
        secondary: "#b66335",
        tertiary: "#f7f7eb",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Digital_Nomad_Life (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6420113,
        file_size_megabytes: 6.12,
        width: 3072,
        height: 5472,
        primary: "#42483a",
        secondary: "#f7ca94",
        tertiary: "#e6ede8",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Digital_Nomad_Life (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5727181,
        file_size_megabytes: 5.46,
        width: 3072,
        height: 5472,
        primary: "#3c4d4c",
        secondary: "#a35735",
        tertiary: "#f7efdc",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Digital_Nomad_Life (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6452150,
        file_size_megabytes: 6.15,
        width: 3072,
        height: 5472,
        primary: "#4c4c42",
        secondary: "#f4c398",
        tertiary: "#ecf4ed",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Futuristic_Interface: {
    environment_title: "Futuristic_Interface",
    images: [
      {
        original_file_name: "Futuristic_Interface (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35217,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#13233c",
        secondary: "#43cbda",
        tertiary: "#cd79ca",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Futuristic_Interface (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37165,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#172335",
        secondary: "#39c8ce",
        tertiary: "#deba61",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Futuristic_Interface (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29324,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#11253b",
        secondary: "#3bcad8",
        tertiary: "#2d7187",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Futuristic_Interface (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28487,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#122235",
        secondary: "#2ad1df",
        tertiary: "#ce9ade",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Futuristic_Interface (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6892446,
        file_size_megabytes: 6.57,
        width: 3072,
        height: 5472,
        primary: "#13233b",
        secondary: "#3fcbdb",
        tertiary: "#d376cb",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Futuristic_Interface (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6779392,
        file_size_megabytes: 6.47,
        width: 3072,
        height: 5472,
        primary: "#172335",
        secondary: "#37c8ce",
        tertiary: "#e0b95d",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Futuristic_Interface (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6606432,
        file_size_megabytes: 6.3,
        width: 3072,
        height: 5472,
        primary: "#12253b",
        secondary: "#38cad7",
        tertiary: "#297187",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Futuristic_Interface (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6237256,
        file_size_megabytes: 5.95,
        width: 3072,
        height: 5472,
        primary: "#122235",
        secondary: "#28d2e0",
        tertiary: "#d498de",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Geometric_Harmony: {
    environment_title: "Geometric_Harmony",
    images: [
      {
        original_file_name: "Geometric_Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 13315,
        file_size_megabytes: 0.01,
        width: 360,
        height: 640,
        primary: "#83b0b8",
        secondary: "#f4e8d6",
        tertiary: "#bbd8d7",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 15254,
        file_size_megabytes: 0.01,
        width: 360,
        height: 640,
        primary: "#6d9d9c",
        secondary: "#f7f0e1",
        tertiary: "#f99f65",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16200,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#5fa5a6",
        secondary: "#e9eae0",
        tertiary: "#86bbb9",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 14763,
        file_size_megabytes: 0.01,
        width: 360,
        height: 640,
        primary: "#264354",
        secondary: "#f0eee4",
        tertiary: "#96c3c2",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Geometric_Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4561689,
        file_size_megabytes: 4.35,
        width: 3072,
        height: 5472,
        primary: "#71a4a9",
        secondary: "#f6d5bf",
        tertiary: "#adcdd4",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4301520,
        file_size_megabytes: 4.1,
        width: 3072,
        height: 5472,
        primary: "#6d9c9b",
        secondary: "#f7f0e2",
        tertiary: "#faa267",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4797689,
        file_size_megabytes: 4.58,
        width: 3072,
        height: 5472,
        primary: "#5fa4a5",
        secondary: "#e9eae0",
        tertiary: "#86bbb9",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Geometric_Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3762626,
        file_size_megabytes: 3.59,
        width: 3072,
        height: 5472,
        primary: "#274353",
        secondary: "#f0eee4",
        tertiary: "#f9ac8c",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Minimalist_Portraits: {
    environment_title: "Minimalist_Portraits",
    images: [
      {
        original_file_name: "Minimalist_Portraits (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 58642,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#333c51",
        secondary: "#e75f46",
        tertiary: "#f4d8b5",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portraits (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 53728,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#2e434b",
        secondary: "#f2c994",
        tertiary: "#eb4f38",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portraits (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51920,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#1e3044",
        secondary: "#ec6a40",
        tertiary: "#e2dac6",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portraits (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44495,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#20283a",
        secondary: "#49aaa5",
        tertiary: "#f0583c",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Minimalist_Portraits (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7702968,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#323c52",
        secondary: "#e95f45",
        tertiary: "#f6d9b6",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portraits (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7472544,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#2d444c",
        secondary: "#f3c993",
        tertiary: "#ec4f38",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portraits (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7158693,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#1d3145",
        secondary: "#ed6a40",
        tertiary: "#e5dac6",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Minimalist_Portraits (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6686703,
        file_size_megabytes: 6.38,
        width: 3072,
        height: 5472,
        primary: "#20283a",
        secondary: "#48aba5",
        tertiary: "#f2583b",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Natures_Geometry: {
    environment_title: "Natures_Geometry",
    images: [
      {
        original_file_name: "Natures_Geometry (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45213,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e6ac7f",
        secondary: "#2f5f6f",
        tertiary: "#8e6056",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Natures_Geometry (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42270,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e5c98d",
        secondary: "#8ad6d2",
        tertiary: "#254e52",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Natures_Geometry (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44468,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#eaab78",
        secondary: "#4f999a",
        tertiary: "#42303b",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Natures_Geometry (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38893,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#eedbab",
        secondary: "#33696f",
        tertiary: "#93d3bf",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Natures_Geometry (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7468111,
        file_size_megabytes: 7.12,
        width: 3072,
        height: 5472,
        primary: "#e7ab7f",
        secondary: "#326c7d",
        tertiary: "#80c2c5",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Natures_Geometry (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7414315,
        file_size_megabytes: 7.07,
        width: 3072,
        height: 5472,
        primary: "#e6c98c",
        secondary: "#8ad6d2",
        tertiary: "#254e52",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Natures_Geometry (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7573162,
        file_size_megabytes: 7.22,
        width: 3072,
        height: 5472,
        primary: "#ebab78",
        secondary: "#4f999a",
        tertiary: "#42313c",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Natures_Geometry (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6687793,
        file_size_megabytes: 6.38,
        width: 3072,
        height: 5472,
        primary: "#efdbaa",
        secondary: "#33696f",
        tertiary: "#93d3c1",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Retro_Tech_Vibes: {
    environment_title: "Retro_Tech_Vibes",
    images: [
      {
        original_file_name: "Retro_Tech_Vibes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 62425,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e1b58e",
        secondary: "#2f2e3f",
        tertiary: "#70afb0",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Retro_Tech_Vibes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 65118,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#e29f72",
        secondary: "#2c3248",
        tertiary: "#71b9bb",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Retro_Tech_Vibes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 54512,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e4ad7c",
        secondary: "#383b4b",
        tertiary: "#77beb5",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Retro_Tech_Vibes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46138,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#dcb391",
        secondary: "#29293c",
        tertiary: "#739fa5",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Retro_Tech_Vibes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8797306,
        file_size_megabytes: 8.39,
        width: 3072,
        height: 5472,
        primary: "#e2b58d",
        secondary: "#2f2e3f",
        tertiary: "#70b0af",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Retro_Tech_Vibes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8784651,
        file_size_megabytes: 8.38,
        width: 3072,
        height: 5472,
        primary: "#e39e70",
        secondary: "#2c3248",
        tertiary: "#6fbabc",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Retro_Tech_Vibes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8404986,
        file_size_megabytes: 8.02,
        width: 3072,
        height: 5472,
        primary: "#e6ac7b",
        secondary: "#383c4c",
        tertiary: "#77beb5",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Retro_Tech_Vibes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7558465,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#ddb390",
        secondary: "#29293c",
        tertiary: "#72a0a5",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  },
  Urban_Jungle: {
    environment_title: "Urban_Jungle",
    images: [
      {
        original_file_name: "Urban_Jungle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46589,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#25493d",
        secondary: "#d7ead9",
        tertiary: "#7fcbb9",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Urban_Jungle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 56051,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#374f32",
        secondary: "#d3e0c4",
        tertiary: "#9abd99",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Urban_Jungle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51592,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#ceebdc",
        secondary: "#2a4539",
        tertiary: "#84b8c3",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Urban_Jungle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48296,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#304736",
        secondary: "#cce0d7",
        tertiary: "#728b6b",
        branch: "Graphic",
        folder: "2D Design",
        type: "min"
      },
      {
        original_file_name: "Urban_Jungle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8759045,
        file_size_megabytes: 8.35,
        width: 3072,
        height: 5472,
        primary: "#25493e",
        secondary: "#d6e9d8",
        tertiary: "#7ecbb9",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Urban_Jungle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9501156,
        file_size_megabytes: 9.06,
        width: 3072,
        height: 5472,
        primary: "#374f32",
        secondary: "#d2dec1",
        tertiary: "#9abd99",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Urban_Jungle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9085569,
        file_size_megabytes: 8.66,
        width: 3072,
        height: 5472,
        primary: "#ceebdb",
        secondary: "#2a4539",
        tertiary: "#84b8c4",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      },
      {
        original_file_name: "Urban_Jungle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10719103,
        file_size_megabytes: 10.22,
        width: 3072,
        height: 5472,
        primary: "#304736",
        secondary: "#cce1d7",
        tertiary: "#728b6b",
        branch: "Graphic",
        folder: "2D Design",
        type: "max"
      }
    ]
  }
};
export default Graphic_2D_Design;
