const Portrait_Moody: Record<string, any> = {
  Eyes_of_Sorrow: {
    environment_title: "Eyes_of_Sorrow",
    images: [
      {
        original_file_name: "Eyes_of_Sorrow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 26837,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b19480",
        secondary: "#1f140f",
        tertiary: "#7f6151",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Eyes_of_Sorrow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28073,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#bda18b",
        secondary: "#241812",
        tertiary: "#8d6956",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Eyes_of_Sorrow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31881,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#513b31",
        secondary: "#bca58f",
        tertiary: "#937864",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Eyes_of_Sorrow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 30762,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#30221b",
        secondary: "#c4b5a2",
        tertiary: "#977f6d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Eyes_of_Sorrow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7147159,
        file_size_megabytes: 6.82,
        width: 3072,
        height: 5472,
        primary: "#b19481",
        secondary: "#20140f",
        tertiary: "#7f6050",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Eyes_of_Sorrow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7451464,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#bda18b",
        secondary: "#241812",
        tertiary: "#8d6956",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Eyes_of_Sorrow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7534043,
        file_size_megabytes: 7.19,
        width: 3072,
        height: 5472,
        primary: "#513c31",
        secondary: "#bca58f",
        tertiary: "#937864",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Eyes_of_Sorrow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7431425,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#30221c",
        secondary: "#c4b5a2",
        tertiary: "#977f6d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Forest_Shadows: {
    environment_title: "Forest_Shadows",
    images: [
      {
        original_file_name: "Forest_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39837,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bcb182",
        secondary: "#131612",
        tertiary: "#6d6a4a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Forest_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46585,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c0b79d",
        secondary: "#161613",
        tertiary: "#706956",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Forest_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45407,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c1ba9b",
        secondary: "#0f110c",
        tertiary: "#6a664d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Forest_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49104,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c1b994",
        secondary: "#151711",
        tertiary: "#6f684a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Forest_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9089257,
        file_size_megabytes: 8.67,
        width: 3072,
        height: 5472,
        primary: "#bcb181",
        secondary: "#131612",
        tertiary: "#6d6a4a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Forest_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9212480,
        file_size_megabytes: 8.79,
        width: 3072,
        height: 5472,
        primary: "#c0b69c",
        secondary: "#171613",
        tertiary: "#6f6956",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Forest_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10085157,
        file_size_megabytes: 9.62,
        width: 3072,
        height: 5472,
        primary: "#c2ba9b",
        secondary: "#0f110c",
        tertiary: "#69664d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Forest_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10185932,
        file_size_megabytes: 9.71,
        width: 3072,
        height: 5472,
        primary: "#c1b993",
        secondary: "#151711",
        tertiary: "#706849",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Golden_Hour_Glow: {
    environment_title: "Golden_Hour_Glow",
    images: [
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32598,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#cb7a38",
        secondary: "#2b1c10",
        tertiary: "#874824",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29760,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ca7830",
        secondary: "#201919",
        tertiary: "#81451b",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32918,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#dea460",
        secondary: "#22160f",
        tertiary: "#7e4522",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36028,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e99e47",
        secondary: "#311a10",
        tertiary: "#925026",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7781797,
        file_size_megabytes: 7.42,
        width: 3072,
        height: 5472,
        primary: "#cc7a36",
        secondary: "#2b1c10",
        tertiary: "#874824",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7473502,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#ca782f",
        secondary: "#201919",
        tertiary: "#82441b",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7475245,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#dfa35f",
        secondary: "#22170f",
        tertiary: "#7e4521",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7940943,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#ea9e46",
        secondary: "#311a0f",
        tertiary: "#925026",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Hands_on_Face: {
    environment_title: "Hands_on_Face",
    images: [
      {
        original_file_name: "Hands_on_Face (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36412,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c5967f",
        secondary: "#130f0d",
        tertiary: "#7a5342",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Hands_on_Face (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36338,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#cda790",
        secondary: "#755142",
        tertiary: "#0e0a08",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Hands_on_Face (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33105,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#be8c74",
        secondary: "#6d4a3b",
        tertiary: "#0d0e10",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Hands_on_Face (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39867,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d6a283",
        secondary: "#7e543e",
        tertiary: "#120b09",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Hands_on_Face (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7855209,
        file_size_megabytes: 7.49,
        width: 3072,
        height: 5472,
        primary: "#c5967f",
        secondary: "#130f0d",
        tertiary: "#7a5342",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Hands_on_Face (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7285020,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#cda690",
        secondary: "#745141",
        tertiary: "#0e0a08",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Hands_on_Face (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7277734,
        file_size_megabytes: 6.94,
        width: 3072,
        height: 5472,
        primary: "#be8c73",
        secondary: "#6d4a3b",
        tertiary: "#0d0e10",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Hands_on_Face (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7585400,
        file_size_megabytes: 7.23,
        width: 3072,
        height: 5472,
        primary: "#d6a283",
        secondary: "#7e543e",
        tertiary: "#120b09",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  RainSoaked_Soul: {
    environment_title: "RainSoaked_Soul",
    images: [
      {
        original_file_name: "RainSoaked_Soul (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43467,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bbab9e",
        secondary: "#161e1b",
        tertiary: "#6a6762",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "RainSoaked_Soul (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36545,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#1c1f1e",
        secondary: "#baa597",
        tertiary: "#656f6c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "RainSoaked_Soul (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37731,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#b29884",
        secondary: "#11191a",
        tertiary: "#705d49",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "RainSoaked_Soul (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40312,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#baaca3",
        secondary: "#161a19",
        tertiary: "#6c6556",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "RainSoaked_Soul (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7410612,
        file_size_megabytes: 7.07,
        width: 3072,
        height: 5472,
        primary: "#bbab9e",
        secondary: "#161e1b",
        tertiary: "#6a6762",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "RainSoaked_Soul (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7319341,
        file_size_megabytes: 6.98,
        width: 3072,
        height: 5472,
        primary: "#1c1f1e",
        secondary: "#baa597",
        tertiary: "#656f6c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "RainSoaked_Soul (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7546610,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#b29984",
        secondary: "#11191a",
        tertiary: "#715d48",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "RainSoaked_Soul (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7370517,
        file_size_megabytes: 7.03,
        width: 3072,
        height: 5472,
        primary: "#b9aca2",
        secondary: "#161a1a",
        tertiary: "#6c6455",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Rainy_Reflection: {
    environment_title: "Rainy_Reflection",
    images: [
      {
        original_file_name: "Rainy_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38195,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bba18e",
        secondary: "#181d1e",
        tertiary: "#6d6259",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35388,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#bcb5ae",
        secondary: "#151616",
        tertiary: "#6b645d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41325,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#b3a18b",
        secondary: "#191a19",
        tertiary: "#766d60",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39494,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1e201d",
        secondary: "#bbc2bc",
        tertiary: "#736b60",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7503665,
        file_size_megabytes: 7.16,
        width: 3072,
        height: 5472,
        primary: "#bba08c",
        secondary: "#181d1e",
        tertiary: "#6d6259",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7209324,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#bbb4ad",
        secondary: "#151617",
        tertiary: "#6a635c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7750837,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#b4a18b",
        secondary: "#191a19",
        tertiary: "#766d60",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7412383,
        file_size_megabytes: 7.07,
        width: 3072,
        height: 5472,
        primary: "#1e201d",
        secondary: "#bbc2bc",
        tertiary: "#736b60",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Shadowed_Solitude: {
    environment_title: "Shadowed_Solitude",
    images: [
      {
        original_file_name: "Shadowed_Solitude (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27306,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c0b9a8",
        secondary: "#130d08",
        tertiary: "#6e6553",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Shadowed_Solitude (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29814,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c39971",
        secondary: "#6b513c",
        tertiary: "#0f0b08",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Shadowed_Solitude (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28432,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b79f86",
        secondary: "#110d09",
        tertiary: "#6c523d",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Shadowed_Solitude (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31681,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c6a37f",
        secondary: "#18130e",
        tertiary: "#75624f",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Shadowed_Solitude (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6542699,
        file_size_megabytes: 6.24,
        width: 3072,
        height: 5472,
        primary: "#c0b9a8",
        secondary: "#130e08",
        tertiary: "#6e6554",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Shadowed_Solitude (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6535727,
        file_size_megabytes: 6.23,
        width: 3072,
        height: 5472,
        primary: "#c39871",
        secondary: "#6b513b",
        tertiary: "#0f0b08",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Shadowed_Solitude (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6602653,
        file_size_megabytes: 6.3,
        width: 3072,
        height: 5472,
        primary: "#b79f85",
        secondary: "#110d09",
        tertiary: "#6c523e",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Shadowed_Solitude (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7038258,
        file_size_megabytes: 6.71,
        width: 3072,
        height: 5472,
        primary: "#c7a37f",
        secondary: "#18140f",
        tertiary: "#766250",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Stormy_Resolve: {
    environment_title: "Stormy_Resolve",
    images: [
      {
        original_file_name: "Stormy_Resolve (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16701,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#101d22",
        secondary: "#a9ada4",
        tertiary: "#56686b",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Stormy_Resolve (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 21156,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#10191c",
        secondary: "#a4b0b2",
        tertiary: "#4f676c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Stormy_Resolve (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 14857,
        file_size_megabytes: 0.01,
        width: 360,
        height: 640,
        primary: "#101b21",
        secondary: "#cdc5b8",
        tertiary: "#61696a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Stormy_Resolve (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 18527,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#0e191e",
        secondary: "#98a29e",
        tertiary: "#788e8c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Stormy_Resolve (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6289392,
        file_size_megabytes: 6.0,
        width: 3072,
        height: 5472,
        primary: "#101d22",
        secondary: "#a9aea4",
        tertiary: "#55686a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Stormy_Resolve (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6806049,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#11191c",
        secondary: "#a4b1b3",
        tertiary: "#536b6f",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Stormy_Resolve (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5968729,
        file_size_megabytes: 5.69,
        width: 3072,
        height: 5472,
        primary: "#101b21",
        secondary: "#cdc5b8",
        tertiary: "#616a6a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Stormy_Resolve (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6738268,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#0e191e",
        secondary: "#98a19e",
        tertiary: "#778e8c",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  TearStreaked_Cheek: {
    environment_title: "TearStreaked_Cheek",
    images: [
      {
        original_file_name: "TearStreaked_Cheek (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37245,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#baa393",
        secondary: "#1c1714",
        tertiary: "#826657",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "TearStreaked_Cheek (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41278,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#be9278",
        secondary: "#1c1513",
        tertiary: "#785240",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "TearStreaked_Cheek (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35713,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#baa190",
        secondary: "#1b1513",
        tertiary: "#795f53",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "TearStreaked_Cheek (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37664,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#be967c",
        secondary: "#1b120f",
        tertiary: "#795443",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "TearStreaked_Cheek (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7286890,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#baa393",
        secondary: "#1d1714",
        tertiary: "#826657",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "TearStreaked_Cheek (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7456841,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#be9177",
        secondary: "#1c1513",
        tertiary: "#785240",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "TearStreaked_Cheek (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7431436,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#bba18f",
        secondary: "#1b1513",
        tertiary: "#795f53",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "TearStreaked_Cheek (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7477876,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#be957b",
        secondary: "#1b120f",
        tertiary: "#795442",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  },
  Veiled_Emotion: {
    environment_title: "Veiled_Emotion",
    images: [
      {
        original_file_name: "Veiled_Emotion (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28362,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b5a094",
        secondary: "#1c1513",
        tertiary: "#77635a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Veiled_Emotion (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33496,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c0b8b4",
        secondary: "#201816",
        tertiary: "#7c726f",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Veiled_Emotion (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34578,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#b99987",
        secondary: "#161212",
        tertiary: "#705e56",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Veiled_Emotion (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35736,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#261f1c",
        secondary: "#c5ac9b",
        tertiary: "#857268",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "min"
      },
      {
        original_file_name: "Veiled_Emotion (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8087845,
        file_size_megabytes: 7.71,
        width: 3072,
        height: 5472,
        primary: "#b5a094",
        secondary: "#1c1513",
        tertiary: "#77635a",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Veiled_Emotion (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8356456,
        file_size_megabytes: 7.97,
        width: 3072,
        height: 5472,
        primary: "#c0b9b4",
        secondary: "#201816",
        tertiary: "#7c726f",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Veiled_Emotion (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8013051,
        file_size_megabytes: 7.64,
        width: 3072,
        height: 5472,
        primary: "#b99987",
        secondary: "#161212",
        tertiary: "#705d56",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      },
      {
        original_file_name: "Veiled_Emotion (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8238282,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#271f1c",
        secondary: "#c5ac9b",
        tertiary: "#847267",
        Branch: "Portrait",
        FolderName: "Moody",
        Type: "max"
      }
    ]
  }
};
export default Portrait_Moody;
