const Portrait_Fashion: Record<string, any> = {
  AvantGarde_Artistry: {
    environment_title: "AvantGarde_Artistry",
    images: [
      {
        original_file_name: "AvantGarde_Artistry (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33819,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#989894",
        secondary: "#1b1816",
        tertiary: "#e2e2de",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "AvantGarde_Artistry (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45079,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bbbab8",
        secondary: "#221a16",
        tertiary: "#eeece8",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "AvantGarde_Artistry (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45490,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c2c1c0",
        secondary: "#322018",
        tertiary: "#6d4838",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "AvantGarde_Artistry (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35826,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#a7a7a3",
        secondary: "#25211f",
        tertiary: "#ece9e4",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "AvantGarde_Artistry (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6574123,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#989894",
        secondary: "#1b1815",
        tertiary: "#e2e1de",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "AvantGarde_Artistry (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6897154,
        file_size_megabytes: 6.58,
        width: 3072,
        height: 5472,
        primary: "#bbbbb8",
        secondary: "#211a16",
        tertiary: "#efece9",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "AvantGarde_Artistry (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7131387,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#c2c1c0",
        secondary: "#6d4838",
        tertiary: "#321f18",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "AvantGarde_Artistry (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6782527,
        file_size_megabytes: 6.47,
        width: 3072,
        height: 5472,
        primary: "#a7a7a3",
        secondary: "#25211f",
        tertiary: "#ede9e4",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Bohemian_Vibes: {
    environment_title: "Bohemian_Vibes",
    images: [
      {
        original_file_name: "Bohemian_Vibes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44385,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#654924",
        secondary: "#dab999",
        tertiary: "#92a9a7",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bohemian_Vibes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48783,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#5b4020",
        secondary: "#9bbabf",
        tertiary: "#dbb997",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bohemian_Vibes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 50279,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#e7ceb0",
        secondary: "#7d5e33",
        tertiary: "#1f190d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bohemian_Vibes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 52152,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#d2a66f",
        secondary: "#917047",
        tertiary: "#1d1b10",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bohemian_Vibes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8665200,
        file_size_megabytes: 8.26,
        width: 3072,
        height: 5472,
        primary: "#654823",
        secondary: "#aab9b3",
        tertiary: "#dab997",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bohemian_Vibes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8633215,
        file_size_megabytes: 8.23,
        width: 3072,
        height: 5472,
        primary: "#5b401f",
        secondary: "#dbb896",
        tertiary: "#9bbac0",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bohemian_Vibes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8330883,
        file_size_megabytes: 7.94,
        width: 3072,
        height: 5472,
        primary: "#e7cdaf",
        secondary: "#7d5e33",
        tertiary: "#1f190d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bohemian_Vibes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8986980,
        file_size_megabytes: 8.57,
        width: 3072,
        height: 5472,
        primary: "#d2a56e",
        secondary: "#917047",
        tertiary: "#1d1b10",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Bold_Statement: {
    environment_title: "Bold_Statement",
    images: [
      {
        original_file_name: "Bold_Statement (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 17856,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#bf7772",
        secondary: "#3a3f41",
        tertiary: "#842f2f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bold_Statement (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 15973,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#41403d",
        secondary: "#cd665c",
        tertiary: "#844647",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bold_Statement (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 19297,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#323031",
        secondary: "#cfa38a",
        tertiary: "#81201e",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bold_Statement (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 17153,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#353b3d",
        secondary: "#d35750",
        tertiary: "#845555",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Bold_Statement (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5994246,
        file_size_megabytes: 5.72,
        width: 3072,
        height: 5472,
        primary: "#bf7771",
        secondary: "#3a3f41",
        tertiary: "#842d2d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bold_Statement (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5859450,
        file_size_megabytes: 5.59,
        width: 3072,
        height: 5472,
        primary: "#41403d",
        secondary: "#ce645b",
        tertiary: "#844647",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bold_Statement (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6218227,
        file_size_megabytes: 5.93,
        width: 3072,
        height: 5472,
        primary: "#323031",
        secondary: "#cfa38a",
        tertiary: "#81201f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Bold_Statement (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6115824,
        file_size_megabytes: 5.83,
        width: 3072,
        height: 5472,
        primary: "#353c3d",
        secondary: "#d3574f",
        tertiary: "#824949",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Classic_Elegance: {
    environment_title: "Classic_Elegance",
    images: [
      {
        original_file_name: "Classic_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25231,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#d0b5a3",
        secondary: "#17120f",
        tertiary: "#725646",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Classic_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 23986,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#cbb2a0",
        secondary: "#2a211a",
        tertiary: "#846b5b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Classic_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 26600,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#e4d3c2",
        secondary: "#8c8577",
        tertiary: "#1e130d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Classic_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25238,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#cfc5bc",
        secondary: "#33312c",
        tertiary: "#a3a49f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Classic_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6561606,
        file_size_megabytes: 6.26,
        width: 3072,
        height: 5472,
        primary: "#d0b6a3",
        secondary: "#17120f",
        tertiary: "#725646",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Classic_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6784573,
        file_size_megabytes: 6.47,
        width: 3072,
        height: 5472,
        primary: "#cbb2a0",
        secondary: "#2a211b",
        tertiary: "#836b5b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Classic_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6657330,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#e3d3c2",
        secondary: "#8c8577",
        tertiary: "#1f130d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Classic_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6090551,
        file_size_megabytes: 5.81,
        width: 3072,
        height: 5472,
        primary: "#cfc5bc",
        secondary: "#33312c",
        tertiary: "#a3a49f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Golden_Hour_Glow: {
    environment_title: "Golden_Hour_Glow",
    images: [
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48229,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#deac6e",
        secondary: "#391909",
        tertiary: "#9d5f30",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 46697,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e7b86e",
        secondary: "#652d0f",
        tertiary: "#1c0a05",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36291,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#f0be70",
        secondary: "#50270f",
        tertiary: "#d09b60",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41102,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e6cc8d",
        secondary: "#5f2b0d",
        tertiary: "#cd7f36",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Golden_Hour_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8447619,
        file_size_megabytes: 8.06,
        width: 3072,
        height: 5472,
        primary: "#dfac6d",
        secondary: "#391908",
        tertiary: "#9d5f2f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8324392,
        file_size_megabytes: 7.94,
        width: 3072,
        height: 5472,
        primary: "#f2d48b",
        secondary: "#703310",
        tertiary: "#270e05",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7682207,
        file_size_megabytes: 7.33,
        width: 3072,
        height: 5472,
        primary: "#633110",
        secondary: "#d6ac72",
        tertiary: "#341609",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Golden_Hour_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8056061,
        file_size_megabytes: 7.68,
        width: 3072,
        height: 5472,
        primary: "#eccd82",
        secondary: "#6e3410",
        tertiary: "#2c1005",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Haute_Couture_Drama: {
    environment_title: "Haute_Couture_Drama",
    images: [
      {
        original_file_name: "Haute_Couture_Drama (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 55441,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c3ad95",
        secondary: "#7d6958",
        tertiary: "#1b130f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Haute_Couture_Drama (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 49986,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c6a78c",
        secondary: "#171515",
        tertiary: "#81664d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Haute_Couture_Drama (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 61313,
        file_size_megabytes: 0.06,
        width: 360,
        height: 640,
        primary: "#d1a37e",
        secondary: "#1f1612",
        tertiary: "#88674a",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Haute_Couture_Drama (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 48356,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c9ab8e",
        secondary: "#1d110c",
        tertiary: "#846851",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Haute_Couture_Drama (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9871383,
        file_size_megabytes: 9.41,
        width: 3072,
        height: 5472,
        primary: "#c3ac94",
        secondary: "#7d6958",
        tertiary: "#1b130f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Haute_Couture_Drama (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8666900,
        file_size_megabytes: 8.27,
        width: 3072,
        height: 5472,
        primary: "#c6a78b",
        secondary: "#161515",
        tertiary: "#81664c",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Haute_Couture_Drama (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9202907,
        file_size_megabytes: 8.78,
        width: 3072,
        height: 5472,
        primary: "#d1a37e",
        secondary: "#1f1611",
        tertiary: "#886648",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Haute_Couture_Drama (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8755250,
        file_size_megabytes: 8.35,
        width: 3072,
        height: 5472,
        primary: "#c9aa8e",
        secondary: "#1d110c",
        tertiary: "#846850",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Layered_Sophistication: {
    environment_title: "Layered_Sophistication",
    images: [
      {
        original_file_name: "Layered_Sophistication (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33339,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#a59f97",
        secondary: "#1d1618",
        tertiary: "#7d5034",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Layered_Sophistication (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39779,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a8a7a3",
        secondary: "#d1b1a0",
        tertiary: "#8c7c6e",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Layered_Sophistication (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 44580,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#caac92",
        secondary: "#2c231e",
        tertiary: "#96755b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Layered_Sophistication (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38369,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bd845c",
        secondary: "#2d231e",
        tertiary: "#8f664a",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Layered_Sophistication (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8550119,
        file_size_megabytes: 8.15,
        width: 3072,
        height: 5472,
        primary: "#a69f95",
        secondary: "#1d1719",
        tertiary: "#7d4f34",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Layered_Sophistication (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9016057,
        file_size_megabytes: 8.6,
        width: 3072,
        height: 5472,
        primary: "#d1b1a0",
        secondary: "#a8a7a3",
        tertiary: "#8c7c6d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Layered_Sophistication (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8566254,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#caac92",
        secondary: "#2c231e",
        tertiary: "#96755a",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Layered_Sophistication (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8732173,
        file_size_megabytes: 8.33,
        width: 3072,
        height: 5472,
        primary: "#be855d",
        secondary: "#2d231e",
        tertiary: "#8f6548",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Monochrome_Magic: {
    environment_title: "Monochrome_Magic",
    images: [
      {
        original_file_name: "Monochrome_Magic (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34009,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#cec4bc",
        secondary: "#2e2c28",
        tertiary: "#867065",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Monochrome_Magic (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 19688,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#d29a79",
        secondary: "#130f0e",
        tertiary: "#7c7168",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Monochrome_Magic (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16791,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#1d1d1e",
        secondary: "#dab196",
        tertiary: "#6c6c6c",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Monochrome_Magic (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16405,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#242321",
        secondary: "#beafa5",
        tertiary: "#6d6a65",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Monochrome_Magic (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6576912,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#cfc4bc",
        secondary: "#2e2c28",
        tertiary: "#867065",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Monochrome_Magic (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5710746,
        file_size_megabytes: 5.45,
        width: 3072,
        height: 5472,
        primary: "#d29979",
        secondary: "#130f0e",
        tertiary: "#7c7067",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Monochrome_Magic (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5135864,
        file_size_megabytes: 4.9,
        width: 3072,
        height: 5472,
        primary: "#1d1d1e",
        secondary: "#dab194",
        tertiary: "#6c6c6c",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Monochrome_Magic (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5292874,
        file_size_megabytes: 5.05,
        width: 3072,
        height: 5472,
        primary: "#242321",
        secondary: "#beaea4",
        tertiary: "#6d6a65",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Neon_Pop: {
    environment_title: "Neon_Pop",
    images: [
      {
        original_file_name: "Neon_Pop (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36294,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ca2a65",
        secondary: "#2dbbc9",
        tertiary: "#1b1230",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Neon_Pop (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38533,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d3396d",
        secondary: "#28c8ea",
        tertiary: "#1d162b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Neon_Pop (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43465,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d12b6e",
        secondary: "#42cce2",
        tertiary: "#19162b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Neon_Pop (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 41645,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#ca3d72",
        secondary: "#2ac2cb",
        tertiary: "#210e1f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Neon_Pop (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8029553,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#ca2a65",
        secondary: "#2ebdcb",
        tertiary: "#1a1230",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Neon_Pop (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7611615,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#d4366d",
        secondary: "#29c6e9",
        tertiary: "#1d162c",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Neon_Pop (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8132998,
        file_size_megabytes: 7.76,
        width: 3072,
        height: 5472,
        primary: "#d12a6e",
        secondary: "#40cce3",
        tertiary: "#19162b",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Neon_Pop (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8226835,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#cc3c71",
        secondary: "#27c2cd",
        tertiary: "#210e1f",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  },
  Street_Style: {
    environment_title: "Street_Style",
    images: [
      {
        original_file_name: "Street_Style (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 45330,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#bea388",
        secondary: "#1f160f",
        tertiary: "#5c361e",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Street_Style (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 43473,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e5caae",
        secondary: "#94baba",
        tertiary: "#201612",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Street_Style (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 42579,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1f1714",
        secondary: "#cdab8e",
        tertiary: "#623d27",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Street_Style (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 47124,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#a88c6f",
        secondary: "#1c1713",
        tertiary: "#52331d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "min"
      },
      {
        original_file_name: "Street_Style (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7633423,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#bea388",
        secondary: "#1f160f",
        tertiary: "#5d361e",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Street_Style (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7814609,
        file_size_megabytes: 7.45,
        width: 3072,
        height: 5472,
        primary: "#e5c9ae",
        secondary: "#93babb",
        tertiary: "#201511",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Street_Style (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7563313,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#1f1714",
        secondary: "#cdab8e",
        tertiary: "#623d26",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      },
      {
        original_file_name: "Street_Style (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7965237,
        file_size_megabytes: 7.6,
        width: 3072,
        height: 5472,
        primary: "#a88c6f",
        secondary: "#1b1713",
        tertiary: "#52331d",
        Branch: "Portrait",
        FolderName: "Fashion",
        Type: "max"
      }
    ]
  }
};
export default Portrait_Fashion;
