import { EnvironmentEntry } from "@/types/database";
const Portrait_Cinematic: Record<string, EnvironmentEntry> = {
  Candlelit_Mystery: {
    environment_title: "Candlelit_Mystery",
    images: [
      {
        original_file_name: "Candlelit_Mystery (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22525,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#bf6721",
        secondary: "#1d0d06",
        tertiary: "#743611",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Candlelit_Mystery (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22300,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#bd6c30",
        secondary: "#1f0c08",
        tertiary: "#7a3c1b",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Candlelit_Mystery (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22280,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#b36b40",
        secondary: "#1d0d07",
        tertiary: "#763a18",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Candlelit_Mystery (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 22359,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#cd925b",
        secondary: "#21100c",
        tertiary: "#7c411f",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Candlelit_Mystery (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6644099,
        file_size_megabytes: 6.34,
        width: 3072,
        height: 5472,
        primary: "#bf6721",
        secondary: "#1d0d06",
        tertiary: "#743611",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Candlelit_Mystery (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6651381,
        file_size_megabytes: 6.34,
        width: 3072,
        height: 5472,
        primary: "#bc6b2f",
        secondary: "#1f0c08",
        tertiary: "#7a3c1a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Candlelit_Mystery (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6657802,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#b36b40",
        secondary: "#1d0d07",
        tertiary: "#763a18",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Candlelit_Mystery (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6872359,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#cd925a",
        secondary: "#21100c",
        tertiary: "#7c411f",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Desert_Wanderer: {
    environment_title: "Desert_Wanderer",
    images: [
      {
        original_file_name: "Desert_Wanderer (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27271,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#abb1af",
        secondary: "#302622",
        tertiary: "#58321d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Desert_Wanderer (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31173,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d29f6d",
        secondary: "#241c1a",
        tertiary: "#708b99",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Desert_Wanderer (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37625,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#e3c4a3",
        secondary: "#a9b8bd",
        tertiary: "#4a2f20",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Desert_Wanderer (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39300,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#c79f76",
        secondary: "#261811",
        tertiary: "#5b341a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Desert_Wanderer (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7216988,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#abb1af",
        secondary: "#302622",
        tertiary: "#58321d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Desert_Wanderer (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7524535,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#d29f6d",
        secondary: "#241d1a",
        tertiary: "#708b99",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Desert_Wanderer (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8273103,
        file_size_megabytes: 7.89,
        width: 3072,
        height: 5472,
        primary: "#e3c4a3",
        secondary: "#a9b8bd",
        tertiary: "#4a2f20",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Desert_Wanderer (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8034809,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#c69e76",
        secondary: "#261811",
        tertiary: "#5b341a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Edge_of_the_Cliff: {
    environment_title: "Edge_of_the_Cliff",
    images: [
      {
        original_file_name: "Edge_of_the_Cliff (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35968,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ba9e7b",
        secondary: "#1c1b1c",
        tertiary: "#704828",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Edge_of_the_Cliff (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 27975,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d2ba94",
        secondary: "#1c1817",
        tertiary: "#766454",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Edge_of_the_Cliff (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 29129,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c9b99f",
        secondary: "#1f1d1b",
        tertiary: "#76614d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Edge_of_the_Cliff (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 37669,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#1e1e1c",
        secondary: "#ccb796",
        tertiary: "#76624a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Edge_of_the_Cliff (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8399001,
        file_size_megabytes: 8.01,
        width: 3072,
        height: 5472,
        primary: "#bb9e7a",
        secondary: "#1c1b1c",
        tertiary: "#6f4827",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Edge_of_the_Cliff (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7287225,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#d2ba94",
        secondary: "#1c1817",
        tertiary: "#766455",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Edge_of_the_Cliff (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7614181,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#cab99f",
        secondary: "#1f1d1b",
        tertiary: "#76614d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Edge_of_the_Cliff (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8241113,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#1e1e1c",
        secondary: "#ccb795",
        tertiary: "#766249",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Forest_Shadows: {
    environment_title: "Forest_Shadows",
    images: [
      {
        original_file_name: "Forest_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 51549,
        file_size_megabytes: 0.05,
        width: 360,
        height: 640,
        primary: "#c9bd93",
        secondary: "#17170f",
        tertiary: "#6f6845",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Forest_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 40731,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cfba92",
        secondary: "#1c1e10",
        tertiary: "#766546",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Forest_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39726,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d1cba6",
        secondary: "#1e1f16",
        tertiary: "#756744",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Forest_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36277,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#ccb286",
        secondary: "#15130b",
        tertiary: "#715b36",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Forest_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7843695,
        file_size_megabytes: 7.48,
        width: 3072,
        height: 5472,
        primary: "#c9bd92",
        secondary: "#17170f",
        tertiary: "#706845",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Forest_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7566708,
        file_size_megabytes: 7.22,
        width: 3072,
        height: 5472,
        primary: "#cfb891",
        secondary: "#1c1e10",
        tertiary: "#766545",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Forest_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7406088,
        file_size_megabytes: 7.06,
        width: 3072,
        height: 5472,
        primary: "#d2cba6",
        secondary: "#1e1f16",
        tertiary: "#766744",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Forest_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7530535,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#cdb285",
        secondary: "#15130b",
        tertiary: "#715b36",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Golden_Hour_Gaze: {
    environment_title: "Golden_Hour_Gaze",
    images: [
      {
        original_file_name: "Golden_Hour_Gaze (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25574,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#cf823c",
        secondary: "#472415",
        tertiary: "#965731",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Hour_Gaze (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 26052,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#e29b53",
        secondary: "#462211",
        tertiary: "#934f27",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Hour_Gaze (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25859,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#eeb76a",
        secondary: "#4d2610",
        tertiary: "#944f1b",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Hour_Gaze (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 25769,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#e69d50",
        secondary: "#25120a",
        tertiary: "#944c1a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Hour_Gaze (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7426079,
        file_size_megabytes: 7.08,
        width: 3072,
        height: 5472,
        primary: "#cf823c",
        secondary: "#472516",
        tertiary: "#965630",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Hour_Gaze (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7180193,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#e29b52",
        secondary: "#462211",
        tertiary: "#924e26",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Hour_Gaze (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7173844,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#eeb76a",
        secondary: "#4d2610",
        tertiary: "#95501a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Hour_Gaze (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7252069,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#e79d50",
        secondary: "#25120a",
        tertiary: "#934b19",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Golden_Spotlight: {
    environment_title: "Golden_Spotlight",
    images: [
      {
        original_file_name: "Golden_Spotlight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 28796,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d4a67d",
        secondary: "#825332",
        tertiary: "#170a05",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Spotlight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34502,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#d29e6a",
        secondary: "#1f0d07",
        tertiary: "#78411e",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Spotlight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39207,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#cf9862",
        secondary: "#1a0a05",
        tertiary: "#7b4722",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Spotlight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 39355,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d4a376",
        secondary: "#18100f",
        tertiary: "#824721",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Golden_Spotlight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6454972,
        file_size_megabytes: 6.16,
        width: 3072,
        height: 5472,
        primary: "#d4a47b",
        secondary: "#825331",
        tertiary: "#170a05",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Spotlight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7338636,
        file_size_megabytes: 7.0,
        width: 3072,
        height: 5472,
        primary: "#d39e69",
        secondary: "#1f0d07",
        tertiary: "#78411d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Spotlight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7301114,
        file_size_megabytes: 6.96,
        width: 3072,
        height: 5472,
        primary: "#d09760",
        secondary: "#1a0a05",
        tertiary: "#7b4721",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Golden_Spotlight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7167697,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#d5a275",
        secondary: "#18100f",
        tertiary: "#814620",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Rainy_Reflection: {
    environment_title: "Rainy_Reflection",
    images: [
      {
        original_file_name: "Rainy_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 38924,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#d2cb98",
        secondary: "#15181c",
        tertiary: "#695543",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32738,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#15171b",
        secondary: "#6fa1ba",
        tertiary: "#c0b8a1",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32668,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c3ad94",
        secondary: "#161518",
        tertiary: "#6fa1b7",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 34953,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#bb8e64",
        secondary: "#131417",
        tertiary: "#6d4f3e",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Rainy_Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7327884,
        file_size_megabytes: 6.99,
        width: 3072,
        height: 5472,
        primary: "#d2cb98",
        secondary: "#15181c",
        tertiary: "#695543",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6866182,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#bfb69f",
        secondary: "#15171b",
        tertiary: "#73a6bf",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7210778,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#c3ad93",
        secondary: "#161518",
        tertiary: "#6fa1b8",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Rainy_Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7131912,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#bb8e63",
        secondary: "#131417",
        tertiary: "#6c4e3d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Shadow_and_Spotlight: {
    environment_title: "Shadow_and_Spotlight",
    images: [
      {
        original_file_name: "Shadow_and_Spotlight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 17011,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#b18262",
        secondary: "#070605",
        tertiary: "#593e2d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Shadow_and_Spotlight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 23348,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#a97043",
        secondary: "#0b0808",
        tertiary: "#633f25",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Shadow_and_Spotlight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 16499,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#b68b70",
        secondary: "#070605",
        tertiary: "#5a4134",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Shadow_and_Spotlight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 21882,
        file_size_megabytes: 0.02,
        width: 360,
        height: 640,
        primary: "#c29d7b",
        secondary: "#0c0807",
        tertiary: "#614738",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Shadow_and_Spotlight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4253406,
        file_size_megabytes: 4.06,
        width: 3072,
        height: 5472,
        primary: "#b08261",
        secondary: "#070605",
        tertiary: "#593d2c",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Shadow_and_Spotlight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5663495,
        file_size_megabytes: 5.4,
        width: 3072,
        height: 5472,
        primary: "#a97043",
        secondary: "#0b0808",
        tertiary: "#624025",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Shadow_and_Spotlight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4202043,
        file_size_megabytes: 4.01,
        width: 3072,
        height: 5472,
        primary: "#b58c6f",
        secondary: "#070605",
        tertiary: "#5b4134",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Shadow_and_Spotlight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5155309,
        file_size_megabytes: 4.92,
        width: 3072,
        height: 5472,
        primary: "#c19d7a",
        secondary: "#0c0807",
        tertiary: "#614737",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Smoke_and_Shadows: {
    environment_title: "Smoke_and_Shadows",
    images: [
      {
        original_file_name: "Smoke_and_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31622,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#bfb3a7",
        secondary: "#161314",
        tertiary: "#6b5a4f",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Smoke_and_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33459,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c2bfaf",
        secondary: "#141114",
        tertiary: "#839497",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Smoke_and_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36546,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c7baa9",
        secondary: "#6d6860",
        tertiary: "#0f1216",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Smoke_and_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 36706,
        file_size_megabytes: 0.04,
        width: 360,
        height: 640,
        primary: "#beb3af",
        secondary: "#0d0f15",
        tertiary: "#8193a4",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Smoke_and_Shadows (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6841402,
        file_size_megabytes: 6.52,
        width: 3072,
        height: 5472,
        primary: "#bfb2a6",
        secondary: "#161314",
        tertiary: "#6b5a4f",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Smoke_and_Shadows (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6748116,
        file_size_megabytes: 6.44,
        width: 3072,
        height: 5472,
        primary: "#c2beaf",
        secondary: "#141114",
        tertiary: "#839499",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Smoke_and_Shadows (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7215099,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#c7baa7",
        secondary: "#6d685f",
        tertiary: "#0f1216",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Smoke_and_Shadows (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6650365,
        file_size_megabytes: 6.34,
        width: 3072,
        height: 5472,
        primary: "#beb2af",
        secondary: "#0d0f14",
        tertiary: "#8193a4",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  },
  Urban_Noir: {
    environment_title: "Urban_Noir",
    images: [
      {
        original_file_name: "Urban_Noir (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 33569,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c3a684",
        secondary: "#111111",
        tertiary: "#68513a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Urban_Noir (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 31697,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#0e1012",
        secondary: "#b7ac99",
        tertiary: "#605b50",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Urban_Noir (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 32162,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c8a56b",
        secondary: "#0f100e",
        tertiary: "#674f2b",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Urban_Noir (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 35301,
        file_size_megabytes: 0.03,
        width: 360,
        height: 640,
        primary: "#c8ad86",
        secondary: "#0d100f",
        tertiary: "#614c2d",
        branch: "Portrait",
        folder: "Cinematic",
        type: "min"
      },
      {
        original_file_name: "Urban_Noir (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6654098,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#c3a682",
        secondary: "#111111",
        tertiary: "#685139",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Urban_Noir (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7192180,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#0e1112",
        secondary: "#b7ab97",
        tertiary: "#605b50",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Urban_Noir (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7224168,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#c8a46a",
        secondary: "#0f100e",
        tertiary: "#684f2a",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      },
      {
        original_file_name: "Urban_Noir (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7471360,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#c8ac84",
        secondary: "#0d1010",
        tertiary: "#614b2c",
        branch: "Portrait",
        folder: "Cinematic",
        type: "max"
      }
    ]
  }
};
export default Portrait_Cinematic;
